### ISSUE TITLE
[missing-firmware] MSI FM2-A22M-E33 (MS-7721)

### ISSUE THREAD

**Issue by abitrolly** [fwupd/lvfs-website#159]
* Link to firmware update at OEM website
https://www.msi.com/Motherboard/support/FM2-A55M-E33

* Firmware release date (if available on OEM website)
2014-02-13
* Link to the device page on LVFS.
None.

---

Unable to update the firmware on this Linux machine, because provided archive contains firmware only in a form if `E7721VB6.exe`, which is a binary USB flasher executable that doesn't work on Windows. It might be possible to extract AMI BIOS firmware from the flasher on Linux, but I haven't found the way so far.

**Comment by hughsie** [comment]
I think the missing firmware is only useful for vendors uploading to the LVFS, sorry. MSI isn't yet supporting the LVFS :(

**Comment by abitrolly** [comment]
They do not support Linux gaming? Do they know why they need to LVFS is they support Linux gamers on Steam (incl. Proton) - are there any page that explains it for Executive/Marketing types of folks?

**Comment by hughsie** [comment]
You can point them at https://people.freedesktop.org/~hughsient/temp/LVFS_Whitepaper.pdf -- they've ignored me so far.

**Comment by abitrolly** [comment]
Is the LVFS an official way to update firmware on Linux?

PDF is good. I would only rephrase the intro.
> LVFS is an online repository for delivering secure firmware updates to hardware. It uses latest industry standards <list of standards> to solve the problem of keeping hardware updated for users, and reduces TCO through universal open source pipeline that adapts well for many vendors. LVFS primarily targets Linux desktop users, but it is also good delivering updates through bootable USB and network devices.

Demonstration of bootable Linux USB or netboot that finds updates for any LVFS supported hardware and installs those updates, would be a compellng argument for executives. Otherwise vendors maintain their own toolchains that get quite outdated, and sometimes are even impossible to follow, like the requirements to burn a CD.

**Comment by abitrolly** [comment]
I could finally extract the firmware from AMI USB tool .exe using the following Python script.

<details>
  <summary>bootextr.py</summary>

```python
'''
After downloading and unpacking B.5 and B.6 firmware from
https://www.msi.com/Motherboard/support/FM2-A55M-E33
the tree structure should look like this

├── 7721vB5
│   ├── 7721vBx.txt
│   ├── E7721AMS.B50
│   └── E7721VB5.exe
├── 7721vB6
│   ├── 7721vBx.txt
│   ├── E7721VB6.exe
│   └── E7721VB6.rar
├── bootextr.py
'''

from pathlib import Path

# https://stackoverflow.com/questions/29850801/subclass-pathlib-path-fails
class File(type(Path())):
  def size(self): 
    return self.stat().st_size

  def open(self, mode='rb'):
    '''Enforce binary mode'''
    if 'b' not in mode:
        mode += 'b'
    return super().open(mode)



fname = '7721vB5/E7721AMS.B50'
fpath = File(fname)
print(fpath.size())
firmB50 = fpath.open().read()
print(len(firmB50))

print('-' * 50)

exename = '7721vB5/E7721VB5.exe'
epath = File(exename)
print(epath.size())
exeB50 = epath.open().read()
print(len(exeB50))

offset = exeB50.find(firmB50)
print(offset)
print(epath.size() - offset)

print('-' * 50)

B60exe = File('7721vB6/E7721VB6.exe').open().read()
print(B60exe.find(firmB50))

# all firmware is of the same size, so read it from 
# the end of file
B60firm = B60exe[-len(firmB50):]
print(len(B60firm))

# for sanity check compare non-zero and non-ff bytes
# from start and from the end of each firmware
matchstart = 0
for i in range(len(B60firm)):
  # https://stackoverflow.com/questions/28249597/why-do-i-get-an-int-when-i-index-bytes
  if firmB50[i] not in (0, 255):
    matchstart += 1
  if firmB50[i] != B60firm[i]:
    break
print('matched from start:', i, '  non 00 FF:', matchstart)

matchend = 0
c = 0
for i in reversed(range(len(B60firm))):
  c += 1
  # https://stackoverflow.com/questions/28249597/why-do-i-get-an-int-when-i-index-bytes
  if firmB50[i] not in (0, 255):
    matchend += 1
  if firmB50[i] != B60firm[i]:
    break
print('matched from end:  ', c, '  non 00 FF:', matchend)

print('-' * 50)

bw = File('E7721AMS.B60').open('wb').write(B60firm)
print(bw, 'bytes written')
```
</details>

```
python3 -i /home/anatoli/MSI/bootextr.py
8388608
8388608
--------------------------------------------------
11256733
11256733
2868125
8388608
--------------------------------------------------
-1
8388608
matched from start: 196708   non 00 FF: 44573
matched from end:   124   non 00 FF: 11
--------------------------------------------------
8388608 bytes written
```
This produces `E7721AMS.B60` file which should be placed on USB flash with FAT16 and them selected from BIOS flash tool.

<details>
  <summary>More notes</summary>

<pre>
https://www.msi.com/Motherboard/FM2-A55M-E33/

Latest BIOS:
- https://www.msi.com/Motherboard/support/FM2-A55M-E33

B.4 2014-02-13 7721vB6.zip http://download.msi.com/bos_exe/mb/7721vB6.zip

B.4 means v11.4 in dmidecode output. I don't know why file is
named 7721. Sometimes there is info that this is MSI-7721 MB,
but the product specification doesn't mention that.

    .
    └── 7721vB6
        ├── 7721vBx.txt
        └── E7721VB6.rar

---

Backing up BIOS produced broken E7721AMS.B40 file, because Fedora 28 USB
drive had insufficient space on partition where the firmware was written.

    483328   May 18 10:11   E7721AMS.B40

Removed all partitions from USB drive leaving only EFI (FAT-12/16/32).
Resized it to 40Mb and backed up firmware from the BIOS.

   8388608   May 18 18:47   E7721AMS.B40

The size matches newer version of firmware downloaded from MSI web site.

   8388608   Dec  2  2013   E7721AMS.B50

However, the download for the latest B.6 firmware contains only Windows
.exe of ATI utility that writes firmware to the USB flash drive. Inside
there are references to new .B60 ATI firmware.

    $ strings 7721vB6/E7721VB6.exe | grep E7721 
    E7721AMS.B60
    E7721AMS.B60
    uP$MSESGN$E7721AMS V11.6 02/12/2015
    E7721AMS.B60
    E7721AMS.B60
    E7721AMS.B60
    $MS1E7721AMSB60

Extracting the firmware for MSI from .exe flasher was simple, because B.5
with raw E7721AMS.B50 also contained similar .exe flasher. The firmware
is attached to the end of the .exe and can be extracted with the Python
script.
</pre>
</details>

If anybody needs the script, it is in public domain.
