### ISSUE TITLE
List all devices on the "Device Details" page (enhancement)

### ISSUE THREAD

**Issue by scottkosty** [fwupd/lvfs-website#184]
On the page https://fwupd.org/lvfs/devicelist, if I click on "Thunderbolt NVM for Xps Notebook 9350", the page appears to be for 9250, not 9350.

Similarly if I click on "Thunderbolt NVM for Precision 5520", the page appears to be for "XPS15 9560 Thunderbolt update".

Is this because they share the same firmware so they share the same "Device Details" page? If so, would it be possible to list all of the devices on the "Device Details" page?

Thanks a lot for all of your work on this project!

**Comment by superm1** [comment]
Yes that's correct on the root cause.

**Comment by scottkosty** [comment]
Thanks for the response. I changed the title of the issue to be more accurate.

**Comment by hughsie** [comment]
Deduped with https://github.com/fwupd/lvfs-website/issues/113
