### ISSUE TITLE
Allow QA users to opt-in to useful emails

### ISSUE THREAD

**Issue by hughsie** [fwupd/lvfs-website#203]
At the moment ODMs manually email the QA of the OEM contact out-of-bad to the LVFS submission process. There has been a request to automatically email the QA contact for the OEM on submission.

I'd like to switch this around, and rather than allowing the uploader to choose a user to email, we get the QA user to opt-in to specific emails. The log here is that the ODM might only know about a few users for the OEM and we don't want to show the full list. We also want to prevent any kind of information disclosure in case the wrong user or email address is chosen, and so the QA user can disable emails (and another QA user can enable them) if they go on holiday for a long time.

I mocked-up the UI I think we should add. It would only show for users with the QA bit set, and would email for any matching firmware in the entire group. We could perhaps also filter by the component ID if needed. Comments and other ideas very welcome.

![screenshot from 2018-12-06 11-27-57](https://user-images.githubusercontent.com/151380/49581926-665c7980-f94b-11e8-8e3c-0ffe5572ee11.png)

**Comment by superm1** [comment]
Sounds like a useful idea to me as long as it stays opt in.
At least for Dell it would only be useful if it could be marked by some whitelist of strings or ESRT GUIDs or something similar per QA person.  Example; some people handle only latitude otherwise don't care.

**Comment by hughsie** [comment]
I think we have something like this now.
