### ISSUE TITLE
Lenovo T460s unresponsive after update

### ISSUE THREAD

**Issue by mikelolasagasti** [fwupd/lvfs-website#244]
* Link to firmware update at OEM website

https://fwupd.org/lvfs/device/63451986-0c42-42db-9a18-342a8455ac68
https://fwupd.org/lvfs/device/42f29620-3d63-4f09-950b-9b7055570f28

* Firmware release date (if available on OEM website)
2018-11-12 03:16:16 & 2018-12-10 01:47:03

* Link to the device page on LVFS.
https://fwupd.org/lvfs/search?value=t460s

**Comment by mikelolasagasti** [comment]
System was able to boot once battery was empty.

```
# fwupdmgr get-history 
20FAS2BN04 System Firmware
  DeviceId:             444a229da2b21bc0d24faf814d1c58c5bff3315f
  Guid:                 42f29620-3d63-4f09-950b-9b7055570f28
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|needs-reboot
  Version:              0.1.11
  Created:              2018-07-28
  Modified:             2018-08-07
  UpdateState:          success
  
  [Release]
  RemoteId:             lvfs
  Version:              0.1.37
  Checksum:             SHA1(6f34562bad74e4c9f7e52ea1e076ad1e753bb9e0)
  TrustFlags:           none
  CpuArchitecture:      x86_64
  RuntimeVersion(org.freedesktop.fwupd): 1.0.8
  CompileVersion(org.freedesktop.fwupd): 1.0.8
  CompileVersion(com.redhat.fwupdate): 10
  SecureBoot:           Disabled
  CompileVersion(org.freedesktop.gusb): 0.3.0
  CompileVersion(org.freedesktop.appstream-glib): 0.7.8
  RuntimeVersion(org.freedesktop.appstream-glib): 0.7.10
  ESPMountPoint:        /boot/efi
  KernelVersion:        4.17.9-200.fc28.x86_64
  UEFIUXCapsule:        Disabled
  RuntimeVersion(com.dell.libsmbios): 2.4
  BootTime:             1532805028
  CompileVersion(com.redhat.efivar): 34

20FAS2BN04 System Firmware
  DeviceId:             444a229da2b21bc0d24faf814d1c58c5bff3315f
  Guid:                 42f29620-3d63-4f09-950b-9b7055570f28
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|needs-reboot
  Version:              0.1.37
  Created:              2018-09-24
  Modified:             2018-09-24
  UpdateState:          success
  
  [Release]
  RemoteId:             lvfs
  Version:              0.1.39
  Checksum:             SHA1(4504f4d680dfca8cd74b1480733cee7737560710)
  TrustFlags:           none
  CpuArchitecture:      x86_64
  RuntimeVersion(org.freedesktop.fwupd): 1.0.9
  CompileVersion(org.freedesktop.fwupd): 1.0.9
  CompileVersion(com.redhat.fwupdate): 11
  SecureBoot:           Disabled
  CompileVersion(org.freedesktop.gusb): 0.3.0
  CompileVersion(org.freedesktop.appstream-glib): 0.7.11
  RuntimeVersion(org.freedesktop.appstream-glib): 0.7.11
  ESPMountPoint:        /boot/efi
  KernelVersion:        4.18.7-200.fc28.x86_64
  UEFIUXCapsule:        Disabled
  RuntimeVersion(com.dell.libsmbios): 2.4
  BootTime:             1537186259
  CompileVersion(com.redhat.efivar): 35

20FAS2BN04 System Firmware
  DeviceId:             444a229da2b21bc0d24faf814d1c58c5bff3315f
  Guid:                 42f29620-3d63-4f09-950b-9b7055570f28
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|needs-reboot
  Version:              0.1.39
  Created:              2019-01-23
  Modified:             2019-01-23
  UpdateState:          needs-reboot
  
  [Release]
  RemoteId:             lvfs
  Version:              0.1.41
  Checksum:             SHA1(cebdf79d47a136a7a92c194d8560343a77397c94)
  TrustFlags:           none
  CpuArchitecture:      x86_64
  RuntimeVersion(org.freedesktop.fwupd): 1.2.3
  DistroId:             fedora
  CompileVersion(org.freedesktop.fwupd): 1.2.3
  CompileVersion(com.redhat.fwupdate): 12
  SecureBoot:           Disabled
  CompileVersion(org.freedesktop.gusb): 0.3.0
  DistroVariant:        workstation
  DistroVersion:        29
  RuntimeVersion(org.freedesktop.appstream-glib): 0.7.14
  ESPMountPoint:        /boot/efi
  KernelVersion:        4.20.3-200.fc29.x86_64
  UEFIUXCapsule:        Disabled
  CompileVersion(com.redhat.efivar): 37
  RuntimeVersion(com.dell.libsmbios): 2.4
  BootTime:             1548244871
  RuntimeVersion(com.redhat.fwupdate): 12

UEFI Device Firmware
  DeviceId:             25127f5d4d5dfd6e903cda1a61a67cb092e4bb0f
  Guid:                 63451986-0c42-42db-9a18-342a8455ac68
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|needs-reboot
  Version:              176.0.1205
  Created:              2019-01-23
  Modified:             2019-01-23
  UpdateState:          needs-reboot
  
  [Release]
  RemoteId:             lvfs
  Version:              184.55.3510
  Checksum:             SHA1(509bfcb29826f6272a7f5a1e8db95a93a7b82e32)
  TrustFlags:           none
  CpuArchitecture:      x86_64
  RuntimeVersion(org.freedesktop.fwupd): 1.2.3
  DistroId:             fedora
  CompileVersion(org.freedesktop.fwupd): 1.2.3
  CompileVersion(com.redhat.fwupdate): 12
  MissingCapsuleHeader: False
  SecureBoot:           Disabled
  CompileVersion(org.freedesktop.gusb): 0.3.0
  DistroVariant:        workstation
  DistroVersion:        29
  RuntimeVersion(org.freedesktop.appstream-glib): 0.7.14
  ESPMountPoint:        /boot/efi
  KernelVersion:        4.20.3-200.fc29.x86_64
  UEFIUXCapsule:        Disabled
  CompileVersion(com.redhat.efivar): 37
  RuntimeVersion(com.dell.libsmbios): 2.4
  BootTime:             1548244871
  RuntimeVersion(com.redhat.fwupdate): 12
```


```
# fwupdmgr report-history 
Target:                  https://fwupd.org/lvfs/firmware/report
Payload:                 {
                           "ReportVersion" : 2,
                           "MachineId" : "5a9be0a71a222249ca0549d82d29fee34c9dd373b729abe19a65887fb7d44854",
                           "Metadata" : {
                             "DistroId" : "fedora",
                             "DistroVersion" : "29",
                             "DistroVariant" : "workstation"
                           },
                           "Reports" : [
                             {
                               "Checksum" : "6f34562bad74e4c9f7e52ea1e076ad1e753bb9e0",
                               "UpdateState" : 2,
                               "Guid" : "42f29620-3d63-4f09-950b-9b7055570f28",
                               "Plugin" : "uefi",
                               "VersionOld" : "0.1.11",
                               "VersionNew" : "0.1.37",
                               "Flags" : 299,
                               "Created" : 1532805108,
                               "Modified" : 1533654383,
                               "Metadata" : {
                                 "CpuArchitecture" : "x86_64",
                                 "RuntimeVersion(org.freedesktop.fwupd)" : "1.0.8",
                                 "CompileVersion(org.freedesktop.fwupd)" : "1.0.8",
                                 "CompileVersion(com.redhat.fwupdate)" : "10",
                                 "SecureBoot" : "Disabled",
                                 "CompileVersion(org.freedesktop.gusb)" : "0.3.0",
                                 "CompileVersion(org.freedesktop.appstream-glib)" : "0.7.8",
                                 "RuntimeVersion(org.freedesktop.appstream-glib)" : "0.7.10",
                                 "ESPMountPoint" : "/boot/efi",
                                 "KernelVersion" : "4.17.9-200.fc28.x86_64",
                                 "UEFIUXCapsule" : "Disabled",
                                 "RuntimeVersion(com.dell.libsmbios)" : "2.4",
                                 "BootTime" : "1532805028",
                                 "CompileVersion(com.redhat.efivar)" : "34"
                               }
                             },
                             {
                               "Checksum" : "4504f4d680dfca8cd74b1480733cee7737560710",
                               "UpdateState" : 2,
                               "Guid" : "42f29620-3d63-4f09-950b-9b7055570f28",
                               "Plugin" : "uefi",
                               "VersionOld" : "0.1.37",
                               "VersionNew" : "0.1.39",
                               "Flags" : 299,
                               "Created" : 1537784403,
                               "Modified" : 1537785847,
                               "Metadata" : {
                                 "CpuArchitecture" : "x86_64",
                                 "RuntimeVersion(org.freedesktop.fwupd)" : "1.0.9",
                                 "CompileVersion(org.freedesktop.fwupd)" : "1.0.9",
                                 "CompileVersion(com.redhat.fwupdate)" : "11",
                                 "SecureBoot" : "Disabled",
                                 "CompileVersion(org.freedesktop.gusb)" : "0.3.0",
                                 "CompileVersion(org.freedesktop.appstream-glib)" : "0.7.11",
                                 "RuntimeVersion(org.freedesktop.appstream-glib)" : "0.7.11",
                                 "ESPMountPoint" : "/boot/efi",
                                 "KernelVersion" : "4.18.7-200.fc28.x86_64",
                                 "UEFIUXCapsule" : "Disabled",
                                 "RuntimeVersion(com.dell.libsmbios)" : "2.4",
                                 "BootTime" : "1537186259",
                                 "CompileVersion(com.redhat.efivar)" : "35"
                               }
                             }
                           ]
                         }

```

**Comment by dawud** [comment]
This has happened to me on a T470s.
Same problem, same "resolution", I had to wait for battery exhaustion before attempting a second upgrade, with ended up OK.
```
# fwupdmgr get-history                                                                                                                                                                                                                                                                                     
UEFI Device Firmware                     
  DeviceId:             cbede50560aaa37366326cd54923421517427f39
  Guid:                 e9124c4a-fdff-42e5-b2ad-f745db345953
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|needs-reboot
  Version:              184.50.3425                             
  Created:              2019-03-02                          
  UpdateState:          needs-reboot
                                                                            
  [Release]                   
  RemoteId:             lvfs      
  Version:              184.55.3510
  Checksum:             SHA1(de53e2814263dddcfe1f01bf866032f8cfe12ac5)
  TrustFlags:           none                                                                                                       
  CpuArchitecture:      x86_64
  RuntimeVersion(org.freedesktop.fwupd): 1.2.5
  DistroId:             fedora
  CompileVersion(org.freedesktop.fwupd): 1.2.5
  CompileVersion(com.redhat.fwupdate): 12                             
  MissingCapsuleHeader: False
  SecureBoot:           Disabled
  DistroVariant:        workstation           
  BootMgrDesc:          legacy                
  CompileVersion(org.freedesktop.gusb): 0.3.0
  DistroVersion:        29      
  RuntimeVersion(org.freedesktop.appstream-glib): 0.7.14
  ESPMountPoint:        /boot/efi                       
  KernelVersion:        4.20.12-200.fc29.x86_64         
  UEFIUXCapsule:        Disabled 
  CompileVersion(com.redhat.efivar): 37        
  RuntimeVersion(com.dell.libsmbios): 2.4
  BootTime:             1551545463     
  RuntimeVersion(com.redhat.fwupdate): 12
                                  
20HGS22D0C System Firmware               
  DeviceId:             84149fb78009cf27cc1dd5520911f46f8792dbfe
  Guid:                 7a176688-0960-47ba-931b-7829849e8347
  Plugin:               uefi                                    
  Flags:                internal|updatable|require-ac|supported|needs-reboot
  Version:              0.1.24
  Created:              2018-08-23                                          
  Modified:             2018-08-23
  UpdateState:          failed    
  UpdateError:          failed to update_prepare using upower: Cannot install update when battery is not at least 30% unless forced
                                    
  [Release]                                                                                                                        
  RemoteId:             lvfs
  Version:              0.1.28
  Checksum:             SHA1(d3f93f01734f37be902cbfd4362d6dd230d20d12)
  TrustFlags:           none  
  CpuArchitecture:      x86_64                                        
  RuntimeVersion(org.freedesktop.fwupd): 1.0.8
  CompileVersion(org.freedesktop.fwupd): 1.0.8
  CompileVersion(com.redhat.fwupdate): 10     
  SecureBoot:           Disabled
  CompileVersion(org.freedesktop.gusb): 0.3.0 
  CompileVersion(org.freedesktop.appstream-glib): 0.7.8
  RuntimeVersion(org.freedesktop.appstream-glib): 0.7.11
  ESPMountPoint:        /boot/efi  
  KernelVersion:        4.17.17-200.fc28.x86_64
  UEFIUXCapsule:        Disabled             
  RuntimeVersion(com.dell.libsmbios): 2.4
  BootTime:             1535048560                      
  CompileVersion(com.redhat.efivar): 34
                                               
20HGS22D0C System Firmware      
  DeviceId:             84149fb78009cf27cc1dd5520911f46f8792dbfe
  Guid:                 7a176688-0960-47ba-931b-7829849e8347
  Plugin:               uefi      
  Flags:                internal|updatable|require-ac|supported|needs-reboot
  Version:              0.1.28
  Created:              2018-11-08
  Modified:             2018-11-08
  UpdateState:          success
  UpdateError:          failed to update_prepare using upower: Cannot install update when battery is not at least 30% unless forced

  [Release]
  RemoteId:             lvfs
  Version:              0.1.30
  Checksum:             SHA1(de43d718570cff5002f939739ced79e44d6e362d)
  TrustFlags:           none
  CpuArchitecture:      x86_64
  RuntimeVersion(org.freedesktop.fwupd): 1.1.4
  CompileVersion(org.freedesktop.fwupd): 1.1.4
  CompileVersion(com.redhat.fwupdate): 12
  SecureBoot:           Disabled
  CompileVersion(org.freedesktop.gusb): 0.3.0
  CompileVersion(org.freedesktop.appstream-glib): 0.7.14
  RuntimeVersion(org.freedesktop.appstream-glib): 0.7.14
  ESPMountPoint:        /boot/efi
  KernelVersion:        4.18.16-300.fc29.x86_64
  UEFIUXCapsule:        Disabled
  CompileVersion(com.redhat.efivar): 35
  RuntimeVersion(com.dell.libsmbios): 2.4
  BootTime:             1541446803
  RuntimeVersion(com.redhat.fwupdate): 12

20HGS22D0C System Firmware
  DeviceId:             84149fb78009cf27cc1dd5520911f46f8792dbfe
  Guid:                 7a176688-0960-47ba-931b-7829849e8347
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|needs-reboot
  Version:              0.1.30
  Created:              2019-03-04
  Modified:             2019-03-04
  UpdateState:          needs-reboot
  UpdateError:          failed to update_prepare using upower: Cannot install update when battery is not at least 30% unless forced

  [Release]
  RemoteId:             lvfs
  Version:              0.1.31
  Checksum:             SHA1(36e4ece71c1d4ee3d5e9035940af05af6d6e6a65)
  TrustFlags:           none
  CpuArchitecture:      x86_64
  RuntimeVersion(org.freedesktop.fwupd): 1.2.5
  DistroId:             fedora
  CompileVersion(org.freedesktop.fwupd): 1.2.5
  CompileVersion(com.redhat.fwupdate): 12
  SecureBoot:           Disabled
  DistroVariant:        workstation
  BootMgrDesc:          legacy
  CompileVersion(org.freedesktop.gusb): 0.3.0
  DistroVersion:        29
  RuntimeVersion(org.freedesktop.appstream-glib): 0.7.14
  ESPMountPoint:        /boot/efi
  KernelVersion:        4.20.13-200.fc29.x86_64
  UEFIUXCapsule:        Disabled
  CompileVersion(com.redhat.efivar): 37
  RuntimeVersion(com.dell.libsmbios): 2.4
  BootTime:             1551684969
  RuntimeVersion(com.redhat.fwupdate): 12
```
```
# fwupdmgr report-history                                                                                                                                                                                                                                                                                             
Target:                  https://fwupd.org/lvfs/firmware/report
Payload:                 {
                           "ReportVersion" : 2,
                           "MachineId" : "26a96d9e381077cbb42441674299559f97c0b085e3049ac8f98278407f1e858d",
                           "Metadata" : {
                             "DistroId" : "fedora",
                             "DistroVersion" : "29",
                             "DistroVariant" : "workstation"
                           },
                           "Reports" : [
                             {
                               "Checksum" : "d3f93f01734f37be902cbfd4362d6dd230d20d12",
                               "UpdateState" : 3,
                               "UpdateError" : "failed to update_prepare using upower: Cannot install update when battery is not at least 30% unless forced",
                               "Guid" : "7a176688-0960-47ba-931b-7829849e8347",
                               "Plugin" : "uefi",
                               "VersionOld" : "0.1.24",
                               "VersionNew" : "0.1.28",
                               "Flags" : 299,
                               "Created" : 1535048874,
                               "Modified" : 1535050019,
                               "Metadata" : {
                                 "CpuArchitecture" : "x86_64",
                                 "RuntimeVersion(org.freedesktop.fwupd)" : "1.0.8",
                                 "CompileVersion(org.freedesktop.fwupd)" : "1.0.8",
                                 "CompileVersion(com.redhat.fwupdate)" : "10",
                                 "SecureBoot" : "Disabled",
                                 "CompileVersion(org.freedesktop.gusb)" : "0.3.0",
                                 "CompileVersion(org.freedesktop.appstream-glib)" : "0.7.8",
                                 "RuntimeVersion(org.freedesktop.appstream-glib)" : "0.7.11",
                                 "ESPMountPoint" : "/boot/efi",
                                 "KernelVersion" : "4.17.17-200.fc28.x86_64",
                                 "UEFIUXCapsule" : "Disabled",
                                 "RuntimeVersion(com.dell.libsmbios)" : "2.4",
                                 "BootTime" : "1535048560",
                                 "CompileVersion(com.redhat.efivar)" : "34"
                               }
                             },
                             {
                               "Checksum" : "de43d718570cff5002f939739ced79e44d6e362d",
                               "UpdateState" : 2,
                               "UpdateError" : "failed to update_prepare using upower: Cannot install update when battery is not at least 30% unless forced",
                               "Guid" : "7a176688-0960-47ba-931b-7829849e8347",
                               "Plugin" : "uefi",
                               "VersionOld" : "0.1.28",
                               "VersionNew" : "0.1.30",
                               "Flags" : 299,
                               "Created" : 1541703183,
                               "Modified" : 1541704185,
                               "Metadata" : {
                                 "CpuArchitecture" : "x86_64",
                                 "RuntimeVersion(org.freedesktop.fwupd)" : "1.1.4",
                                 "CompileVersion(org.freedesktop.fwupd)" : "1.1.4",
                                 "CompileVersion(com.redhat.fwupdate)" : "12",
                                 "SecureBoot" : "Disabled",
                                 "CompileVersion(org.freedesktop.gusb)" : "0.3.0",
                                 "CompileVersion(org.freedesktop.appstream-glib)" : "0.7.14",
                                 "RuntimeVersion(org.freedesktop.appstream-glib)" : "0.7.14",
                                 "ESPMountPoint" : "/boot/efi",
                                 "KernelVersion" : "4.18.16-300.fc29.x86_64",
                                 "UEFIUXCapsule" : "Disabled",
                                 "CompileVersion(com.redhat.efivar)" : "35",
                                 "RuntimeVersion(com.dell.libsmbios)" : "2.4",
                                 "BootTime" : "1541446803",
                                 "RuntimeVersion(com.redhat.fwupdate)" : "12"
                               }
                             }
                           ]
                         }
Proceed with upload? [Y|n]: Y
Upload message: d3f93f01734f37be902cbfd4362d6dd230d20d12 replaces old report
```
```
# fwupdmgr report-history
No reports require uploading

```

**Comment by ealcaniz** [comment]
This has happened to me on a T470s.
Same problem, same "resolution", I had to wait for battery exhaustion before attempting a second upgrade, with ended up OK.


[ealcaniz@ealcaniz ~]$ fwupdmgr get-history 
20HGS22D15 System Firmware
  DeviceId:             84149fb78009cf27cc1dd5520911f46f8792dbfe
  Guid:                 7a176688-0960-47ba-931b-7829849e8347
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|needs-reboot
  Version:              0.1.30
  Created:              2019-03-30
  UpdateState:          needs-reboot
  
  [Release]
  RemoteId:             lvfs
  Version:              0.1.32
  Checksum:             SHA1(7200c2035fb952d196a341182a5b11a65804470d)
  TrustFlags:           none
  CpuArchitecture:      x86_64
  RuntimeVersion(org.freedesktop.fwupd): 1.2.5
  DistroId:             fedora
  CompileVersion(org.freedesktop.fwupd): 1.2.5
  CompileVersion(com.redhat.fwupdate): 12
  SecureBoot:           Disabled
  DistroVariant:        workstation
  BootMgrDesc:          legacy
  CompileVersion(org.freedesktop.gusb): 0.3.0
  DistroVersion:        29
  RuntimeVersion(org.freedesktop.appstream-glib): 0.7.14
  ESPMountPoint:        /boot/efi
  KernelVersion:        5.0.3-200.fc29.x86_64
  UEFIUXCapsule:        Disabled
  CompileVersion(com.redhat.efivar): 37
  RuntimeVersion(com.dell.libsmbios): 2.4
  BootTime:             1553868515
  RuntimeVersion(com.redhat.fwupdate): 12

UEFI Device Firmware
  DeviceId:             cbede50560aaa37366326cd54923421517427f39
  Guid:                 e9124c4a-fdff-42e5-b2ad-f745db345953
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|needs-reboot
  Version:              184.55.3510
  Created:              2019-03-30
  UpdateState:          needs-reboot
  
  [Release]
  RemoteId:             lvfs
  Version:              184.60.3561
  Checksum:             SHA1(a1a9c2e6f464fc3c6174afe55dd5f8b5027ac3bc)
  TrustFlags:           none
  CpuArchitecture:      x86_64
  RuntimeVersion(org.freedesktop.fwupd): 1.2.5
  DistroId:             fedora
  CompileVersion(org.freedesktop.fwupd): 1.2.5
  CompileVersion(com.redhat.fwupdate): 12
  MissingCapsuleHeader: False
  SecureBoot:           Disabled
  DistroVariant:        workstation
  BootMgrDesc:          legacy
  CompileVersion(org.freedesktop.gusb): 0.3.0
  DistroVersion:        29
  RuntimeVersion(org.freedesktop.appstream-glib): 0.7.14
  ESPMountPoint:        /boot/efi
  KernelVersion:        5.0.3-200.fc29.x86_64
  UEFIUXCapsule:        Disabled
  CompileVersion(com.redhat.efivar): 37
  RuntimeVersion(com.dell.libsmbios): 2.4
  BootTime:             1553868515
  RuntimeVersion(com.redhat.fwupdate): 12

20HGS22D15 System Firmware
  DeviceId:             84149fb78009cf27cc1dd5520911f46f8792dbfe
  Guid:                 7a176688-0960-47ba-931b-7829849e8347
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|needs-reboot
  Version:              0.1.14
  Created:              2018-10-31
  Modified:             2018-11-01
  UpdateState:          success
  
  [Release]
  RemoteId:             lvfs
  Version:              0.1.30
  Checksum:             SHA1(de43d718570cff5002f939739ced79e44d6e362d)
  TrustFlags:           none
  CpuArchitecture:      x86_64
  RuntimeVersion(org.freedesktop.fwupd): 1.0.9
  CompileVersion(org.freedesktop.fwupd): 1.0.9
  CompileVersion(com.redhat.fwupdate): 11
  SecureBoot:           Disabled
  CompileVersion(org.freedesktop.gusb): 0.3.0
  CompileVersion(org.freedesktop.appstream-glib): 0.7.11
  RuntimeVersion(org.freedesktop.appstream-glib): 0.7.11
  ESPMountPoint:        /boot/efi
  KernelVersion:        4.18.16-200.fc28.x86_64
  UEFIUXCapsule:        Disabled
  RuntimeVersion(com.dell.libsmbios): 2.4
  BootTime:             1541021227
  CompileVersion(com.redhat.efivar): 35

20HGS22D15 System Firmware
  DeviceId:             84149fb78009cf27cc1dd5520911f46f8792dbfe
  Guid:                 7a176688-0960-47ba-931b-7829849e8347
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|needs-reboot
  Version:              0.1.30
  Created:              2019-02-26
  Modified:             2019-02-28
  UpdateState:          needs-reboot
  
  [Release]
  RemoteId:             lvfs
  Version:              0.1.31
  Checksum:             SHA1(36e4ece71c1d4ee3d5e9035940af05af6d6e6a65)
  TrustFlags:           none
  CpuArchitecture:      x86_64
  RuntimeVersion(org.freedesktop.fwupd): 1.2.3
  DistroId:             fedora
  CompileVersion(org.freedesktop.fwupd): 1.2.3
  CompileVersion(com.redhat.fwupdate): 12
  SecureBoot:           Disabled
  CompileVersion(org.freedesktop.gusb): 0.3.0
  DistroVariant:        workstation
  DistroVersion:        29
  RuntimeVersion(org.freedesktop.appstream-glib): 0.7.14
  ESPMountPoint:        /boot/efi
  KernelVersion:        4.20.10-200.fc29.x86_64
  UEFIUXCapsule:        Disabled
  CompileVersion(com.redhat.efivar): 37
  RuntimeVersion(com.dell.libsmbios): 2.4
  BootTime:             1551163952
  RuntimeVersion(com.redhat.fwupdate): 12

UEFI Device Firmware
  DeviceId:             cbede50560aaa37366326cd54923421517427f39
  Guid:                 e9124c4a-fdff-42e5-b2ad-f745db345953
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|needs-reboot
  Version:              184.50.3425
  Created:              2019-02-26
  Modified:             2019-02-28
  UpdateState:          success
  
  [Release]
  RemoteId:             lvfs
  Version:              184.55.3510
  Checksum:             SHA1(de53e2814263dddcfe1f01bf866032f8cfe12ac5)
  TrustFlags:           none
  CpuArchitecture:      x86_64
  RuntimeVersion(org.freedesktop.fwupd): 1.2.3
  DistroId:             fedora
  CompileVersion(org.freedesktop.fwupd): 1.2.3
  CompileVersion(com.redhat.fwupdate): 12
  MissingCapsuleHeader: False
  SecureBoot:           Disabled
  CompileVersion(org.freedesktop.gusb): 0.3.0
  DistroVariant:        workstation
  DistroVersion:        29
  RuntimeVersion(org.freedesktop.appstream-glib): 0.7.14
  ESPMountPoint:        /boot/efi
  KernelVersion:        4.20.10-200.fc29.x86_64
  UEFIUXCapsule:        Disabled
  CompileVersion(com.redhat.efivar): 37
  RuntimeVersion(com.dell.libsmbios): 2.4
  BootTime:             1551163952
  RuntimeVersion(com.redhat.fwupdate): 12

[ealcaniz@ealcaniz ~]$ fwupdmgr report-history 
Target:                  https://fwupd.org/lvfs/firmware/report
Payload:                 {
                           "ReportVersion" : 2,
                           "MachineId" : "bc65d29d1e189307f396705089591da9dbc6d06589354d3bde8e07ecc931031b",
                           "Metadata" : {
                             "DistroId" : "fedora",
                             "DistroVersion" : "29",
                             "DistroVariant" : "workstation"
                           },
                           "Reports" : [
                             {
                               "Checksum" : "de43d718570cff5002f939739ced79e44d6e362d",
                               "UpdateState" : 2,
                               "Guid" : "7a176688-0960-47ba-931b-7829849e8347",
                               "Plugin" : "uefi",
                               "VersionOld" : "0.1.14",
                               "VersionNew" : "0.1.30",
                               "Flags" : 299,
                               "Created" : 1541021258,
                               "Modified" : 1541057165,
                               "Metadata" : {
                                 "CpuArchitecture" : "x86_64",
                                 "RuntimeVersion(org.freedesktop.fwupd)" : "1.0.9",
                                 "CompileVersion(org.freedesktop.fwupd)" : "1.0.9",
                                 "CompileVersion(com.redhat.fwupdate)" : "11",
                                 "SecureBoot" : "Disabled",
                                 "CompileVersion(org.freedesktop.gusb)" : "0.3.0",
                                 "CompileVersion(org.freedesktop.appstream-glib)" : "0.7.11",
                                 "RuntimeVersion(org.freedesktop.appstream-glib)" : "0.7.11",
                                 "ESPMountPoint" : "/boot/efi",
                                 "KernelVersion" : "4.18.16-200.fc28.x86_64",
                                 "UEFIUXCapsule" : "Disabled",
                                 "RuntimeVersion(com.dell.libsmbios)" : "2.4",
                                 "BootTime" : "1541021227",
                                 "CompileVersion(com.redhat.efivar)" : "35"
                               }
                             },
                             {
                               "Checksum" : "de53e2814263dddcfe1f01bf866032f8cfe12ac5",
                               "UpdateState" : 2,
                               "Guid" : "e9124c4a-fdff-42e5-b2ad-f745db345953",
                               "Plugin" : "uefi",
                               "VersionOld" : "184.50.3425",
                               "VersionNew" : "184.55.3510",
                               "Flags" : 299,
                               "Created" : 1551164091,
                               "Modified" : 1551335781,
                               "Metadata" : {
                                 "CpuArchitecture" : "x86_64",
                                 "RuntimeVersion(org.freedesktop.fwupd)" : "1.2.3",
                                 "DistroId" : "fedora",
                                 "CompileVersion(org.freedesktop.fwupd)" : "1.2.3",
                                 "CompileVersion(com.redhat.fwupdate)" : "12",
                                 "MissingCapsuleHeader" : "False",
                                 "SecureBoot" : "Disabled",
                                 "CompileVersion(org.freedesktop.gusb)" : "0.3.0",
                                 "DistroVariant" : "workstation",
                                 "DistroVersion" : "29",
                                 "RuntimeVersion(org.freedesktop.appstream-glib)" : "0.7.14",
                                 "ESPMountPoint" : "/boot/efi",
                                 "KernelVersion" : "4.20.10-200.fc29.x86_64",
                                 "UEFIUXCapsule" : "Disabled",
                                 "CompileVersion(com.redhat.efivar)" : "37",
                                 "RuntimeVersion(com.dell.libsmbios)" : "2.4",
                                 "BootTime" : "1551163952",
                                 "RuntimeVersion(com.redhat.fwupdate)" : "12"
                               }
                             }
                           ]
                         }

**Comment by jeffgoh** [comment]
Sigh. Mine just did same with recent firmware. Gonna pull the external battery and wait.

**Comment by hughsie** [comment]
This was a bug in the "old" Lenovo firmware. Waiting for the battery to exhaust is a perfectly valid fix, although not awesome at all. I've very much made Lenovo aware of this.
