### ISSUE TITLE
missing firmware for DELL optiplex 3040

### ISSUE THREAD

**Issue by duperray** [fwupd/lvfs-website#260]
For missing firmware please provide the following items:

* Link to firmware update at OEM website
https://www.dell.com/support/home/us/en/19/drivers/driversdetails?driverid=ptwpv&oscode=wb64a&productcode=optiplex-3040m-desktop
this is bios version 1.9.0
* Firmware release date (if available on OEM website)
21 Dec 2018
* Link to the device page on LVFS.

https://fwupd.org/lvfs/device/d63450d6-d611-48ac-8f3b-8d29bad80248
last update 1.8.2

**Comment by superm1** [comment]
That one you linked to on LVFS is for the 3046 (the 3040 is the last generation), but I'll check with the team (

**Comment by duperray** [comment]
it seems to be the right link on LVFS, the name is incorrect (according to bios names proposed on that
same page)
the link for the optiplex 3046 is there:
https://fwupd.org/lvfs/device/91dbf191-d8ed-447b-af42-2e8fbf10f7ca

this wrong 3040/3046 link has already been reported in this comment:
https://github.com/hughsie/lvfs-website/issues/164#issuecomment-422779491

thanks for your time

**Comment by duperray** [comment]
are the guid in the url related to one of the guid returned by:
`#> fwupdmgr get-devices`
(or should)?

Regards,

Pierre

**Comment by superm1** [comment]
Something is wonky is going on with the combining, but I believe the 3040 FW should be there now.
