### ISSUE TITLE
Allow for vendor specific readme file in uploaded LVFS package or other suitable place

### ISSUE THREAD

**Issue by GavinChengGao** [fwupd/lvfs-website#286]
We have a need to include a vendor specific readme file into LVFS package to describe what we think necessary for end user to know. But based on test, such a readme file will be auto removed after the original LVFS pacakge get signed in LVFS website. Expect to support this feature in a proper way.

**Comment by hughsie** [comment]
My gut instinct here is to whitelist `*.txt` or `*.rtf` files -- but ideas welcome. @superm1?

**Comment by superm1** [comment]
In practice will anyone actually see these files? 
Think of the normal flow.

1. Someone gets a prompt in gnome software for an update.
2. They click it and they see the changelog/fixes.
3. They decide to install it, and hit the install button.
4. fwupd stages the update to ESP.
5. Prompt to reboot.
6. Reboot the machine and BIOS flashes the update.

So where in that flow would someone see a text file?
Is the thought that they manually go to fwupd.org and download the CAB and double click it and that's what renders in `gnome-software` or `fwupdmgr get-details $CAB` ?

So I guess that begs the question; what kind of content will be in this proposed vendor specific README?  If it's really something they need to see I feel like it should:
* actually go into the metainfo XML file under a new section
* LVFS allow you to fill this out manually
* `fwupd` grow support to display it
* GUI frontends like `gnome-software` and `kde discover` grow support to display it

**Comment by hughsie** [comment]
I think the idea was to have some kind of document explaining what was tested, e.g. on what fwupd/fuwpdate versions and also how to debug if things go wrong, e.g. what Fn key to press to get to the boot menu.

If we do want to put this kind of content in the metainfo file, I guess the toplevel <description> makes the most sense - not the update description but the generic device description that's deduped between components with the same AppStream ID.

**Comment by superm1** [comment]
> I think the idea was to have some kind of document explaining what was tested, e.g. on what fwupd/fuwpdate version

I feel like there are better ways to show this than a static README.  Like think about how fwupd reports get sent to LVFS?  LVFS could render a list of successful tool versions "publicly" with the firmware.

The inverse can be done too, if there are failures reported on a particular client version, a warning can be put in the metadata when there is some sort of threshold of failures happening  lients with that version combination will show a warning when installing or even not offer the update.

> If we do want to put this kind of content in the metainfo file, I guess the toplevel makes the most sense - 

I would much rather see it in metainfo file, at least then all the tools that need to parse CAB don't need to start parsing multiple files.

**Comment by hughsie** [comment]
> I would much rather see it in metainfo file, at least then all the tools that need to parse CAB don't need to start parsing multiple files.

I think I agree. We should add the required data into the existing metainfo.xml file in a structured way where it's required.
