### ISSUE TITLE
Unable to support long release notes

### ISSUE THREAD

**Issue by superm1** [fwupd/lvfs-website#319]
I was notified by my team that the 255 character limit is too small for LVFS today on some platforms.

I was given this example:
https://www.dell.com/support/home/us/en/19/drivers/driversdetails?driverid=fp5kd&oscode=wt64a&productcode=precision-5820-workstation

For that platform there was a TON of CVEs. 

Could you bump that up?  That release has ~850 characters.

**Comment by hughsie** [comment]
> I was notified by my team that the 255 character limit is too small for LVFS today on some platforms.

Do you think users read all that text? I agree 255 chars is on the
small side, but I don't think the answer is just to make the
entry/database column larger.

> Could you bump that up?

I'd rather have some structured details. If we included the CVE
numbers in the metadata properly then they'll be clickable, and the
users can see what each CVE actually fixes and if it applies to them.

**Comment by superm1** [comment]
Well I guess look at the link I sent.  It's got a grouping of a bunch of CVEs that are tied to a larger security advisory.  I think if you're going to make it structured that concept needs to remain.

Here's my idea.
1. Break the "Release description" dialog into 3 sections: Security Fixes, Fixes, Enhancements
2. In the security fixes section show a default of say 4 lines of boxes.
3. In the left "Security advisory" (empty for none).
4. In the right CVE-IDs, comma separated.

Then that would encourage splitting them up, but I would worry that older clients won't know what to do with this information to put it back together.

That being said making CVE IDs clickable doesn't require structured format.  Just need to append the things that look like CVE IDs to https://nvd.nist.gov/vuln/detail/ and that would be enough.

**Comment by hughsie** [comment]
What was the exact problem -- was it `Paragraphs is too long, limit is 300 chars`? I was looking today and I couldn't find any 255 char limit anywhere, although the validator does have quite a few style checks that it might be.

> Here's my idea

I think it's a good idea, but I think we'd need to treat it a bit like the bugzilla bug entry process where you can have an escape hatch of "just plain text" or a "helper" that puts together nice prose from the 4 split up sections.

**Comment by superm1** [comment]
> What was the exact problem

They didn't mention the actual error message to me.  They were trying to add the exact same release notes as the Windows release so maybe that's one that it was flagging.

> I think it's a good idea, but I think we'd need to treat it a bit like the Bugzilla bug entry process where you can have an escape hatch of "just plain text" or a "helper" that puts together nice prose from the 4 split up sections.

Maybe a hidden form field by same name as current that can be released by a button (and also still scriptable)?

**Comment by hughsie** [comment]
> They were trying to add the exact same release notes as the Windows release

I've just tried that and got:

    Release is not valid!
    Paragraphs is too long, limit is 300 chars and was 401...
    Paragraphs is too short, minimum is 12 chars and was 6: [Fixes:]

By changing the `Fixes:` to `This release fixes the following issues:` fixed the second error, and removing the not-update-text-IMHO `BIOS is a firmware that is embedded on a small memory chip on the computer's system board. It controls the keyboard, monitor, disk drives and other devices.` removed the first warning.

**Comment by hughsie** [comment]
> that puts together nice prose from the 4 split up sections

I was thinking about this a bit last night too; I'd really like to push vendors to put the update text into the metainfo.xml file rather than finding it simpler to edit online. Of course, the other solution is to rewrite the .metainfo.xml file (and thus resign the .cab file) although that's going to break all kinds of other things as we find we've got three files for the same upload that all have different SHA hashes.

Perhaps we want to only sign when going from private->* rather than on upload. Just thinking aloud here.

**Comment by superm1** [comment]
At least for Dell UEFI capsules they're generated via automation.  The changelog that will be made public is not available at that time, so I don't see a solution to actually putting the updated content into `metainfo.xml` for Dell.

I don't think that rewriting the CAB is a good idea if there was already an MS signature contained within it.  I don't know how Windows would handle the CAB if a file it doesn't use but is referenced in the CAT changed.  Otherwise it does work for both OSes in those circumstances.

**Comment by hughsie** [comment]
> if there was already an MS signature contained within it

Well, we've already destroyed that by adding firmware.bin.asc in that case then...

**Comment by superm1** [comment]
Well looking through https://docs.microsoft.com/en-us/windows-hardware/drivers/install/catalog-files maybe it doesn't actually matter.  If the XML wasn't described in the CopyFiles directive, it might just be ignored.

> Perhaps we want to only sign when going from private->* rather than on upload. Just thinking aloud here.

Stable is treated as a special case though that metadata can't be modified again.  I think that would be the only time it would make sense to repack the CAB file with modified XML if you are going to do it.  You're right it does mean 3 CAB file hashes to worry about: upload hash, initial signing hash, and stable signed hash.  As long as they can all be associated back to the same firmware # I don't think it's a "big" deal.  The corner case that comes to mind is that if you have embargo and stable both enabled on a machine then while promoting to stable it needs to be removed from the embargo remote rather than stored in both.
