### ISSUE TITLE
Support vendor "mapping" for severities

### ISSUE THREAD

**Issue by superm1** [fwupd/lvfs-website#320]
Since the update urgency has been made compulsory I've received feedback from people using it that it doesn't have a clear mapping to the terms that are used internally to Dell so it's not clear what urgency to use.  Instead there is guessing and inconsistency.

**LVFS:**
* Low
* Medium
* High
* Critical

**Dell**
* Not Defined
* Optional
* Recommended
* Urgent

So I'd ask if it would be possible to apply a field mapping to show Dell strings instead of LVFS strings at when someone is signed in with a Dell OEM account.

**Comment by hughsie** [comment]
> Not Defined

Is this really to be mapped to "low"? Not defined is more 'unknown'
and thus wouldn't be allowed to be pushed to stable. As something
general to support I think it's a good idea.

**Comment by superm1** [comment]
Well actually "not defined" is treated specially in that urgency wouldn't be rendered I believe.  I would be fine just removing it when these alternate strings were used.
