### ISSUE TITLE
Missing firmware for Dell TB16 dock

### ISSUE THREAD

**Issue by pachulo** [fwupd/lvfs-website#364]
I think that this version is not in LVFS, but I'm not really sure.

* Link to firmware update at OEM website
https://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverid=7TJ1H&oscode=W732&productcode=dell-thunderbolt-dock-tb16

* Firmware release date (if available on OEM website)
03 Jan 2019

* Link to the device page on LVFS.
https://fwupd.org/lvfs/device/com.dell.mstbe025b25.firmware

**Comment by superm1** [comment]
That's correct, the TB16 does not have a firmware update for all components in LVFS currently.  The MST hub is the only component in LVFS.

**Comment by pachulo** [comment]
Should it be possible to have all of them then?

**Comment by superm1** [comment]
Sorry, not currently.

**Comment by pachulo** [comment]
OK, thanks for the info & all the work you do!
