### ISSUE TITLE
Duplicate firmwares for same system names, different content

### ISSUE THREAD

**Issue by StricUmu** [fwupd/lvfs-website#373]
Searching for "optiplex 7060" gives
https://fwupd.org/lvfs/search?value=optiplex+7060
which lists two entries, both named "OptiPlex 7060 System Update" with same versions, but they list different content - one of them is for "HPD"(?). Hard to know which one is for me.

**Comment by hughsie** [comment]
@superm1 perhaps we need some kind of "component variant", or perhaps just a suffix on the existing `<name>`. Any insight you can share would be useful. Thanks.

**Comment by superm1** [comment]
I believe this tends to happen if we have a system with two different possible BIOS images.

There are two reasons I know this has happened:
1. Different CPU (for example -U vs -H)
2. certain technology is not available in certain regions

For both of those reasons most people won't know what they need. The reliable way to match is via UEFI ESRT GUID.

**Comment by superm1** [comment]
Regarding the 7060 and 7070 showing up in the same link it looks like it's caused by non-unique ESRT GUID use (which I think we should do https://github.com/hughsie/lvfs-website/issues/342 to prevent in the future).

The 7070 will need a CHID applied.  I'll pull it back out of stable to avoid confusion until the team does it.

**Comment by hughsie** [comment]
@superm1 do you think we need a "component variant" for the different ESRTs with the same `<name>` and category?

**Comment by superm1** [comment]
I think that could help.  Maybe a key called `<family>` that can be included in the XML for platforms that have a grouping of ESRT values available.
