### ISSUE TITLE
Proposal for ODM to be completely responsible for all parts of the LVFS process on behalf of OEM

### ISSUE THREAD

**Issue by GavinChengGao** [fwupd/lvfs-website#380]
Although LVFS now can mark the ODM as being able to push to testing/stable on behalf of OEM, we want to go further to have ODM to be completely responsible for all parts of the LVFS process, but to have the OEM group credited and aware of the work on the LVFS. This means:
1.After ODM‘s promotion/demotion, OEM key members can be automatically notified (possibley by their registered email) about the event for auditing the change.
2.After ODM‘s promotion to public testing/stable, ODM vendor account won’t appear in the search results or the vendor list, making it hidden to all users except ones from the OEM. What appears to users are still OEM brands.
Expect this to be supported to offload OEM's effort for regular LVFS package distribution work so that we can focus on more value-added features.

**Comment by superm1** [comment]
There has been discussion on this concept @ https://github.com/hughsie/lvfs-website/pull/377

**Comment by hughsie** [comment]
I'm on PTO this week but am planning to work on this feature next week. I think we need to:

[ ] define which OEMs/ODMs are allowed to manage which AppStream ID prefixes
[ ] add attributes to the affiliate relationship object
[ ] move existing firmware managed by the odm to the oem account

More detail will be required, I'm sure.
