### ISSUE TITLE
Dell TPM firmware upgrade keeps downgrading to embargo

### ISSUE THREAD

**Issue by superm1** [fwupd/lvfs-website#383]
There are a bunch of really "old" reports of failures that I suspect are causing it to get downgraded.    Certainly since last time it was brought back to stable there were no new negative reports.

https://fwupd.org/lvfs/firmware/130

**Comment by hughsie** [comment]
Should we limit the downgrade to reports uploaded within the last 6 months perhaps?

**Comment by hughsie** [comment]
> there were tons of negative reports due to how people configured fwupd

Can we add a known issue rule? Then the negatives get converted to known-issue and don't get used as part of the calculation.
