### ISSUE TITLE
deleted firmware still appears in dashboard

### ISSUE THREAD

**Issue by xnlcasad** [fwupd/lvfs-website#384]
Would you consider removing deleted firmware from the 'dashboard' and from 'show all' ?

We believe deleted firmware should only be shown in the 'deleted' category, to avoid cluttering the view.

**Comment by hughsie** [comment]
> Would you consider removing deleted firmware from the 'dashboard' 

Do you mean hiding it from "Recently uploaded firmware" -- if so, I agree. I'll work on that now.

> and from 'show all' ?

Hmm, _All_ kind of implies all firmware, regardless of state. I was pondering removing the "all" filter as some vendors have hundreds of firmwares. Either we remove it, or we have to add some kind of pagination to the search results.

**Comment by xnlcasad** [comment]
> Do you mean hiding it from "Recently uploaded firmware"

Yes, but maybe also on that same page when you click on 'show all' at the bottom of the list. Maybe that 'show all' could be 'show all recent'

> Hmm, All kind of implies all firmware, regardless of state.

'show all' means all. Ok. This 'show all' is the one on the left pane, next to the other categories.

**Comment by hughsie** [comment]
> Maybe that 'show all' could be 'show all recent'

Lets take a step back; what are you trying to do? If I can understand the workflow maybe we can do something better than just adding yet another filtered view.

**Comment by xnlcasad** [comment]
We're looking at all firmwares and investigating which have update problems, and we'd like to see all applicables ones, this includes those in embargo/testing/stable. But not those on deleted. That's all.

**Comment by hughsie** [comment]
Is "Telemetry->Success" better suited for that?

**Comment by xnlcasad** [comment]
Yeah, we can use that. Let's close the issue. The intention was to unclutter the dashboard by removing the 'deleted' firmware, I think that's fixed with your PR.
