### ISSUE TITLE
Search result list and actual page names differ

### ISSUE THREAD

**Issue by paulmenzel** [fwupd/lvfs-website#399]
On https://fwupd.org/lvfs/ the search result for *tb16* shows two entries.

1.  [TB16 VMM3320 MST Device Update](https://fwupd.org/lvfs/device/com.dell.mst0a52c8c7.firmware)
2.  [TB16 VMM3330 MST Device Update](https://fwupd.org/lvfs/device/com.dell.mstbe025b25.firmware)

Note, the different 2 and 3 in the name. Actually clicking on the result, both pages are titled for *3320*.

**Comment by hughsie** [comment]
This is because the update targets the VMM3320, VMM3330 and VMM3332 -- we probably ought to list all components in the device list.

**Comment by superm1** [comment]
The same firmware actually applies to both components too in this case.

**Comment by hughsie** [comment]
Closed in favour of https://github.com/fwupd/lvfs-website/issues/113
