### ISSUE TITLE
Create per-vendor repos for missing firmware

### ISSUE THREAD

**Issue by hughsie** [fwupd/lvfs-website#401]
This would allow, for instance, Lenovo to "watch" a repo without getting notifications about all the different lvfs-website issues.

**Comment by superm1** [comment]
This was the idea behind labels, but I'm not sure you can get notifications on just labels.

**Comment by hughsie** [comment]
And also, non-maintainers can't add their own labels :( I'll try a new repo for Lenovo and see how it works.

**Comment by hughsie** [comment]
It works, and gets the issues list under control. I can now look at the issues list and find things that need fixing on the LVFS :)
