### ISSUE TITLE
In the new website redesign, a lot of content is not separated by headings

### ISSUE THREAD

**Issue by thomas-t-w** [fwupd/lvfs-website#408]
https://fwupd.org/lvfs/devicelist
The old website used headings to separate brands and recent firmware on the website. The website redesign does not do this and instead just uses a larger font to simulate headings. This makes it difficult for screen reader users like myself to navigate the site.

**Comment by hughsie** [comment]
Ohh, sorry about that, I hadn't considered screen readers when switching to bootstrap cards. Would changing `<div class="card-title">Latest firmware on the LVFS</div>` to `<h2 class="card-title">Latest firmware on the LVFS</h2>` be the sort of change that would help?

**Comment by thomas-t-w** [comment]
That would be perfect. A good rule of thumb generally is to try avoid using divs for anything like a heading or control that can be clicked because the screen reader can't provide context such as whether it is a readio button or a checkbox etc. That can't be done in all cases and ARIA exists for those cases but that is certainly not required here.

**Comment by hughsie** [comment]
Sorry this took so long to fix....
