### ISSUE TITLE
A few update protocol related items

### ISSUE THREAD

**Issue by superm1** [fwupd/lvfs-website#414]
A few things that I noticed about update protocol that should be sorted out.

1. Need to add new protocol for the eMMC plugin (`org.jedec.mmc`)
2. it would be easier to find items if the list was sorted by the display string instead of the (seemingly) random order.
2. There is a testing protocol listed:
![image](https://user-images.githubusercontent.com/494526/67207665-a3055800-f3d9-11e9-87e3-4f1f32d53732.png)

**Comment by hughsie** [comment]
> Need to add new protocol for the eMMC plugin (org.jedec.mmc)

How do i answer these questions?

*  Cryptographically signed images or transfer, e.g. GPG, PKCS-7, X509
* Can verify checksum on device 

I guess the 2nd one is false, but the first?

**Comment by superm1** [comment]
I think i'd say false for both of them for now until someone told us otherwise - and even then it might be device specific.
