### ISSUE TITLE
demote should go to testing rather than embargo

### ISSUE THREAD

**Issue by superm1** [fwupd/lvfs-website#420]
I've been messaged a few times from people who aren't sure what happened to firmware because it completely disappears from LVFS when there are enough reported failures.

Principally I have no problem with the downgrades, I think they make sense to prevent more failures.  However I think they should go to `testing` instead.  Then at least people who know there are a bunch of reports coming in with failures but still want to get the firmware can get it.

**Comment by hughsie** [comment]
Makes sense to me. Can you do a PR? I'm afk most of this week.
