### ISSUE TITLE
New firmware page could contain FW component name too

### ISSUE THREAD

**Issue by joakim-tjernlund** [fwupd/lvfs-website#423]
Today it reads
```
When | Hardware | Version 
a day ago | Lenovo       ThinkPad X1 Carbon 6th | 0.1.18
```
Would be much nicer if it read:
```
When | Component | Hardware | Version
a day ago | Embedded Controller N23HT33W | Lenovo       ThinkPad X1 Carbon 6th | 0.1.18
```

**Comment by hughsie** [comment]
There are multiple components in one update, but I do understand what you mean. Do you want to have a go at a pull request for this?

**Comment by joakim-tjernlund** [comment]
well, If spoke www language I could but I have no clue :(

**Comment by joakim-tjernlund** [comment]
When will this hit the www service?

**Comment by hughsie** [comment]
Probably Monday, deploying anything on a Friday is a bad idea :)

**Comment by joakim-tjernlund** [comment]
I see the new page now, thanks.There is no separation between HW/Component, it reads as one
long sentence.
