### ISSUE TITLE
https://fwupd.org/lvfs/docs/metainfo/version should be updated for recommended version

### ISSUE THREAD

**Issue by superm1** [fwupd/lvfs-website#433]
Things have changed now:
* triplet is not the default - unknown is.  
* for uefi lvfs will fall back to vendor defaults
* lvfs will show warnings if you don't have a version format specified for anything non uefi.

So I think the wording should change to make the key recommended in most instances instead.

**Comment by hughsie** [comment]
> for uefi lvfs will fall back to vendor defaults

This isn't something that's available to new vendors, I'm only making this available to the three vendors that were uploading UEFI firmware before LVFS::VersionFormat metadata was requested.

**Comment by superm1** [comment]
> This isn't something that's available to new vendors, I'm only making this available to the three vendors that were uploading UEFI firmware before LVFS::VersionFormat metadata was requested.

OK makes sense.
