### ISSUE TITLE
Need a page of helpful consulting companies

### ISSUE THREAD

**Issue by hughsie** [fwupd/lvfs-website#440]
Background: I don't scale https://blogs.gnome.org/hughsie/2019/11/18/google-and-fwupd/

What I'd like to see on the LVFS is a page of consulting companies that the silicon suppliers and ODMs can pay money to and avoid having myself as the central point of failure. Those companies would need to be free-software friendly, understand the ecosystem and be competent enough to be recommended by us.

My proposal would be to add a text field to the LVFS `Vendor` which marks them as available for consulting work, providing a paragraph or two about the services they provide and a single clickable link to their contact information (which is probably different to the generic website URL).

Then when I get asked about how to support widget X, Y, or Z I can refer on the company to a subset of suppliers that understand the difference between downstream and upstream, and spaces v.s. tabs...

**Comment by superm1** [comment]
> from Christmas onwards the “Designed for ChromeBook” sticker requires hardware vendors to use fwupd rather than random non-free binaries

If that's what is happening, I think a really important step should be for Google to commit some resourcing to keeping fwupd healthy as well.  Hopefully someone who matters reaches out in this regard.

> My proposal would be to add a text field to the LVFS Vendor which marks them as available for consulting work, providing a paragraph or two about the services they provide and a single clickable link to their contact information (which is probably different to the generic website URL).

I actually think a separate page might be a better way.  The number of companies that do consulting is going to be a very small subset of the companies on the vendors page.  That and there may be consulting companies that don't actually participate in LVFS or fwupd.  I think of a company like Collabora could fit that bill.

**Comment by hughsie** [comment]
> I think a really important step should be for Google to commit some resourcing to keeping fwupd healthy as well

Tell me about it.  *crickets*

> I actually think a separate page might be a better way

What about something like this?

![Screenshot_2019-11-18 LVFS Consulting Services](https://user-images.githubusercontent.com/151380/69074575-8d5e6f00-0a27-11ea-9fc4-3bd1751d53f9.png)

**Comment by superm1** [comment]
I think that looks really good.  I think that a lot of the stuff in your blog post should translate into that page too.  FYI something else you might consider is making vendors bring their discussions to the mailing lists when possible.  There's always a few things that need a private email, but I would suspect a majority of the nuts and bolts can come to mailing lists after some pleasantries and banging on the head around the bullets from that blog post.

**Comment by hughsie** [comment]
Something like this?


The consulting company will need to know some details to accurately quote for work, and this list will also help upstream to review your new plugin. 

Specifications on the update protocol. If an NDA is required to view this, then it will take much longer. An alternate approach is to relicence the existing update code under a LGPLv2+ license so it can be used as a basis for a new plugin. From experience, not much of the legacy code will be used in the final pull request but the error defines and function names might be similar. You should talk to your legal team about how hard relicensing the existing codebase would be if no formal specification exists.

If you are running Linux, and want upstream to debug or test your new plugin, you need to be running an up-to-date distribution. I know your customers might be running Debian Stable or Ubuntu LTS, but that’s not what upstream is using. Consulting companies will be able to get this code upstream, and probably won’t be able to build packages for much older Linux distributions.

If you want to design and write all of the plugin yourself, that’s great, but please follow the existing style and don’t try to wrap your existing code base with the fwupd plugin API. If your device has three logical children with different version numbers or firmware formats, upstream will want to see three devices in fwupdmgr. If you need to restrict the child devices to a parent vendor, that’s supported already.

If you’re using an nonstandard firmware format (as in, not DFU, Intel HEX or Motorola SREC) then someone will need to write a firmware parser that’s memory safe. The consulting company will need all the header/footer documentation so they can verify the parser and add some small redistributable fuzz targets. If the blob is being passed to the hardware without parsing, they still might need to know the format of the header so that the plugin can do a sanity check that the firmware is suitable for the hardware, and that any internal CRC is actually correct. All the firmware parsers have to be totally paranoid and written defensively.

Anyone doing plugin development is probably going to ask for test hardware, and two different versions of the firmware that can actually be flashed to the test hardware. A bare PCB is usually fine. If you send hardware to someone, ensure you also include a power supply.

You need to think how to present your device version number. e.g. is 0x12345678 meant to be presented as “12.34.5678” or “18.52.86.120” – the LVFS really cares if this is correct, and users want to see the “same” version numbers as on the OEM web-page.

You also need to know if the device is fully functional during the update, or if it operates in a degraded or bootloader mode. The plugin needs to know what happens if flashing fails, e.g. is the device a brick, or is there some kind of A/B partition that makes a flash failure harmless? If the device is a brick, how can it be recovered without an RMA?

After the update is complete fwupd needs to “restart” the device so that the new firmware version can be verified, so there needs to be some kind of command the device understands – we can ask the user to reboot or re-plug the device if this is the only way to do this, although typically we can really do better than that.

If you’re sending a huge code archive, the person reading it will need access to someone who actually understands it, preferably the person that wrote it in the first place.

Once a plugin exists in fwupd and is upstream, it is usually considered further work to create pull requests to add either more VID/PIDs, #defines or to add variations to the protocol for new versions of the hardware. No consultant will be able to push all the VID/PIDs to Debian stable. Most will have zero control on when Debian backports anything, and very little influence on when Ubuntu does a SRU. The upstream maintainer uses Fedora and so it’s somewhat easier to get new hardware support into that.

**Comment by khilman** [comment]
BayLibre (www.baylibre.com) is an upstream-focused consultancy, very active in the kernel community[1], as well as u-boot, yocto, etc. and helping our customers ship linux based products (including OTA updates, firmware etc.)  We're available for hire for this kind of work.

[1] https://lwn.net/Articles/804119/

**Comment by superm1** [comment]
> If you are running Linux, and want upstream to debug or test your new plugin, you need to be running an up-to-date distribution. I know your customers 

I think you should avoid using the words "I know"

>might be running Debian Stable or Ubuntu LTS, but that’s not what upstream is using. Consulting companies will be able to get this code upstream, and probably won’t be able to build packages for much older Linux distributions.

Well that's not necessarily true, I use both Debian and Ubuntu on lots of stuff 😸 
I think a better way is to focus on the importance of the code working upstream and against all CI targets.  Leave the getting it into older distributions and stuff that those of us working on it don't use out of the equation.

>If you want to design and write all of the plugin yourself, that’s great, but please follow the existing style and don’t try to wrap your existing code base with the fwupd plugin API. If your device has three logical children with different version numbers or firmware formats, upstream will want to see three devices in fwupdmgr. If you need to restrict the child devices to a parent vendor, that’s supported already.

Depends where this whole section lands if this part makes sense.  Although it's important information it's probably best off in one of the introductory pages that links to this consulting page (inverse it so it's "If you want to write a plugin, keep these things in mind, otherwise go look here at all this other stuff")

> You need to think how to present your device version number. e.g. is 0x12345678 meant to be presented as “12.34.5678” or “18.52.86.120” – the LVFS really cares if this is correct, and users want to see the “same” version numbers as on the OEM web-page.

Link to versionformat page for this.

>After the update is complete fwupd needs to “restart” the device so that the new firmware version can be verified, so there needs to be some kind of command the device understands – we can ask the user to reboot or re-plug the device if this is the only way to do this, although typically we can really do better than that.

Avoid the usage of "we" in this paragraph.  

>Once a plugin exists in fwupd and is upstream, it is usually considered further work to create pull requests to add either more VID/PIDs, #defines or to add variations to the protocol for new versions of the hardware. No consultant will be able to push all the VID/PIDs to Debian stable. Most will have zero control on when Debian backports anything, and very little influence on when Ubuntu does a SRU. The upstream maintainer uses Fedora and so it’s somewhat easier to get new hardware support into that.

A proposal for the last few sentences:

Most consultants typically are unable to directly modify existing distribution stable releases, but they may be able to work with maintainers in those distributions to make these requests.  Some distributions such as Fedora update their software stack regularly, so the newest hardware support will typically be available there first.

**Comment by hughsie** [comment]
@khilman can you email me two paragraphs of prose text please, and include a single URL we can use for the more info button please.

**Comment by andhe** [comment]
Hi,

[Endian Technologies AB](https://endian.se/) is interested in being listed.

**Comment by hughsie** [comment]
Hey @andhe -- can you email me two paragraphs of corporate-friendly text explaining a bit about Endian Techologies and the services you provide, along with a link for the "more info" button -- that would be great. Thanks!
