### ISSUE TITLE
Should allow alternate version for each component

### ISSUE THREAD

**Issue by hughsie** [fwupd/lvfs-website#444]
Some vendors have a "formal" version like `1.30` and also an optional easy to identify version-like string that identifies that version for a specific model. In the Lenovo case it would be something like `N1NET43W` and I think it would be a good idea to store it in the database rather than the vendor putting it free form in the update description. Splitting it out means it's searchable, and means we can automatically add it in the `md.version_display` output, e.g. `1.30 (N1NET43W)`

As usual the hardest part is the naming! Ideas I was pondering was `version_alternate` or `version_id` but other ideas welcome.

@superm1 -- any ideas?

**Comment by superm1** [comment]
I'm confused - so is this essentially just version for display?

**Comment by hughsie** [comment]
> this essentially just version for display

Basically, yes. It's like a "marketing name" for the version.

**Comment by superm1** [comment]
If you add this field I would like to also do it "automatically" from UEFI updates that take it from INF if not filled out. Would finally solve the 0.1.1.1 meaning 1.1.1 on Dell BIOS..

**Comment by hughsie** [comment]
> take it from INF

Yes, I suppose with this the per-Firmware version_display can migrate to a per-Component version_display.

> Would finally solve the 0.1.1.1 meaning 1.1.1 on Dell BIOS

**Comment by hughsie** [comment]
> Would finally solve the 0.1.1.1 meaning 1.1.1 on Dell BIOS

not so convinced by that one, I think it would be rendered as `0.1.1.1 (1.1.1)` which is just more confusing I think. The more I think about this, the more I wonder if we want a `dell` version format which is just `BB.CC.DD`

**Comment by superm1** [comment]
> Basically, yes. It's like a "marketing name" for the version.

So shouldn't it be formatted as `Marketing name (formal name)` as in:
 `N1NET43W (1.30)`

Or just have two separate fields, `VersionDisplay` and `Version`.  We've already got raw version and string version, so this could just be one more.

> not so convinced by that one, I think it would be rendered as 0.1.1.1 (1.1.1) which is just more confusing I think. The more I think about this, the more I wonder if we want a dell version format which is just BB.CC.DD

If they're split up as separate keys I would argue that we should have `fwupdmgr get-devices` show version_display under `current_version` the key if it exists and `version` if not.

**Comment by hughsie** [comment]
> we should have fwupdmgr get-devices show version_display under current_version the key if it exists and version if not

We can't have AppStream metadata affect the device properties. I've resisted all calls for this so far as it's a slippery slope that ends in a pile of hacks.

**Comment by hughsie** [comment]
Fixed in https://github.com/fwupd/lvfs-website/commit/2f243f7ccd9935bf3f873376b318d4798e7afa9b
