### ISSUE TITLE
Feature Request: RSS feed for device pages

### ISSUE THREAD

**Issue by bjoern-tantau** [fwupd/lvfs-website#447]
It would be nice to have an RSS feed available on the device pages (like https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN27ET.firmware) to be notified of new releases in case you're waiting for something specific.

**Comment by hughsie** [comment]
I guess this makes sense, but I have no experience with RSS at all. Is this something you can help with?

**Comment by bjoern-tantau** [comment]
I don't have much experience with Python. ;-)

But I'll try to hack something together. I'd simply output to another template when called with an `rss` query parameter.

**Comment by bjoern-tantau** [comment]
I added a pull request (atom instead of RSS, as it is newer and allows for full HTML content) in #448, but the timestamps aren't formatted correctly yet. Although I suspect that most feed readers will be able to handle the current format it would be better if they got the correct format.

**Comment by hughsie** [comment]
Merged, and deployed. Thanks!
