### ISSUE TITLE
Need a LVFS Metadata Specification V2

### ISSUE THREAD

**Issue by hughsie** [fwupd/lvfs-website#454]
Problem
=======

 * An old detached signature could be downloaded with new metadata = error message on the client as it looks "unsigned"
 * There are lots of hardcoded assumptions about the metadata name
 * We use the signing key as the epoch, which doesn't work without signing support
 * No explicit checksums, so we rely on signing for download checking
 * We don't know how large the metadata download (or signature for that matter) is going to be, and it's 200Kb now, and only going to be getting bigger...

Prior Art
=========

repomd
------

 - Used for yum/dnf metadata
 - XML so not as "cool" as JSON nowadays - but matches AppStream...
 - Not 'scoped' and so multiple repomd files would be needed for each remote. Not a totally bad thing; we don't want to leak the list of embargoed remotes anyway.
 - Contains the size, so we could prompt the user "Are you sure you want to download 1.2Mb on this restricted connection...." for instance
 - Contains the checksum, so we can validate the correct download of unsigned metadata (or GPG signed metadata, with GPG client-side disabled)
 - Has existing tools that can parse and modify the files, e.g. `modifyrepo_c`

TUF
----

  - Very complicated for our needs, as we always serve files over SSL, and without a mirror
  - Increases the number and size of downloaded files
  - Has many "layers" of signing authority, which doesn't reflect the centralized nature of the LVFS
  - Does allow replacing the signing key, which is easier than updating the fwupd package in Debian stable...
  - Uses by other distributed repositories at scale
  - Too complicated for a simple example

Proposals
=========

A subset of the repomd metadata format:

    <?xml version="1.0" encoding="UTF-8"?>
    <repomd>
     <revision>17</revision>
     <data type="primary-v1">
       <checksum type="sha256">feb74872025056442b66aca1575f40f12a3b196abf42ca5f7bdd1d2d7b9d3ed9</checksum>
       <location href="metadata-rev000017-v1.xml.gz"/>
       <timestamp>1571741027</timestamp>
       <size>68597</size>
     </data>
     <data type="primary-v1-pkcs7">
       <checksum type="sha256">4a13d00f9c28f8bd4416e6414f18fdc970b498c065e98d1c46e9918bcbd42786</checksum>
       <location href="metadata-rev000017-v1.xml.gz.p7b"/>
       <timestamp>1571741027</timestamp>
       <size>627</size>
     </data>
     <data type="primary-v1-gpg">
       <checksum type="sha256">4a13d00f9c28f8bd4416e6414f18fdc970b498c065e98d1c46e9918bcbd42786</checksum>
       <location href="metadata-rev000017-v1.xml.gz.asc"/>
       <timestamp>1571741027</timestamp>
       <size>627</size>
     </data>
    </repomd>

At metadata creation time, we delete any metadata revisions older than `revision - 2` so we keep 3 versions of the metadata on the server.

At download time, we download the `repomd.xml` file to `/var/lib/fwupd/remotes.d/`remote`/repomd.xml`.
Changes in the checksum of the `repomd.xml` file would cause the metadata and optionally any signature to be downloaded too.

So perhaps we actually want the repomd to be as small as possible, and not include multiple "versions" of the same metadata, e.g.

    <?xml version="1.0" encoding="UTF-8"?>
    <repomd>
     <revision>1571741027</revision>
     <data type="primary">
       <checksum type="sha256">feb74872025056442b66aca1575f40f12a3b196abf42ca5f7bdd1d2d7b9d3ed9</checksum>
       <location href="metadata-rev1571741027.xml.gz"/>
       <size>68597</size>
     </data>
     <data type="primary-pkcs7">
       <checksum type="sha256">4a13d00f9c28f8bd4416e6414f18fdc970b498c065e98d1c46e9918bcbd42786</checksum>
       <location href="metadata-rev1571741027.xml.gz.p7b"/>
       <size>627</size>
     </data>
     <data type="primary-gpg">
       <checksum type="sha256">4a13d00f9c28f8bd4416e6414f18fdc970b498c065e98d1c46e9918bcbd42786</checksum>
       <location href="metadata-rev1571741027.xml.gz.asc"/>
       <size>627</size>
     </data>
    </repomd>

This means the client could request something like `https://cdn.fwupd.org/metadata/v1` rather than `https://cdn.fwupd.org/downloads/firmware.xml.gz`

I do wonder if a more restful thing would be to do `/metadata/v1` to get the pregenerated `metadata.xml.gz` and then `/metadata/v1/pkcs7/{sha256_of_xml_gz}` although that has the same problems where we don't know the size of the metadata or the checksums. It also doesn't allow us to do the trick where we download the tiny .asc to check if the metadata has changed from yesterday.

Maybe we do `/metadata/v1/repomd.xml` to get the pre-generated `repomd.xml`:

    <?xml version="1.0" encoding="UTF-8"?>
    <repomd>
     <revision>1571741027</revision>
     <data type="primary">
       <checksum type="sha256">feb74872025056442b66aca1575f40f12a3b196abf42ca5f7bdd1d2d7b9d3ed9</checksum>
       <location href="metadata.xml.gz"/>
       <size>68597</size>
     </data>
     <data type="pkcs7">
       <checksum type="sha256">4a13d00f9c28f8bd4416e6414f18fdc970b498c065e98d1c46e9918bcbd42786</checksum>
       <location href="metadata.xml.gz.p7b"/>
       <size>627</size>
     </data>
     <data type="gpg">
       <checksum type="sha256">4a13d00f9c28f8bd4416e6414f18fdc970b498c065e98d1c46e9918bcbd42786</checksum>
       <location href="metadata.xml.gz.asc"/>
       <size>627</size>
     </data>
    </repomd>

And then do `/metadata/v1/pkcs7/{sha256_of_metadata_xml_gz}` to ensure we always get the right file rather than what's been symlinked most recently.

 * We need to store the sha256 checksums of the metadata in a database table, along with a timestamp to be able to delete metadata older than say 2 days.
 * The CDN would like this, as it looks like a new request for each SHA rather than relying on the cache timeout for `metadata.xml.gz`
 * We'd still need to cache invalidate for `v1/repomd.xml` like we do already

Compatibity
===========

The latest revision of the metadata of each type is symlinked into the legacy metadata.xml.gz-style and the legacy clients would just completely ignore `repomd.xml` and download the files *directly* like before.

Bumping the revision of the metadata (e.g. to include `<name_variant_suffix>`) can be done by writing out a new v2 metadata, which would have different SHA256 checksums. The client would just be switched out to request `v2/repomd.xml`

Things we could fix
===================

 * `name_variant_suffix`
 * `category`
 * add CVEs as metadata
 * enforce relative download paths in the .xml.gz

**Comment by hughsie** [comment]
@superm1 comments very welcome, I'm aware this is yet another brain-dump.

**Comment by superm1** [comment]
I think it's pretty well thought out.  The one thing I would ask though is why even bother having the signature detached anymore?  If it means an extra download request every time, you might be able to decrease number of downloads quite a bit if you combine them.

I guess compatibility with older clients is the primary reason, but you can also generate a "legacy" metadata using detached signatures for a while too.

> I do wonder if a more restful thing would be to do /metadata/v1 to get the pregenerated metadata.xml.gz and then /metadata/v1/pkcs7/{sha256_of_xml_gz} although that has the same problems where we don't know the size of the metadata or the checksums. It also doesn't allow us to do the trick where we download the tiny .asc to check if the metadata has changed from yesterday.

I think that does make the repomd approach seem nicer, however how often does LVFS metadata change these days?  I would have to guess daily now isn't it?

> So perhaps we actually want the repomd to be as small as possible, and not include multiple "versions" of the same metadata, e.g.

I agree - keep it as small as possible.  Use another vanity URL to hit older versions of it if needed for some reason.

> This means the client could request something like https://cdn.fwupd.org/metadata/v1

This seems like an opportunity to have `/metadata/v1` and `/metadata` point at the same thing.  If all fwupd clients are configured to https://cdn.fwupd.org/metadata it seems sensible to me that you just serve the content that https://cdn.fwupd.org/metadata/v1 would have.

**Comment by superm1** [comment]
> This seems like an opportunity to have /metadata/v1 and /metadata point at the same thing. If all fwupd clients are configured to https://cdn.fwupd.org/metadata it seems sensible to me that you just serve the content that https://cdn.fwupd.org/metadata/v1 would have.

Ah sorry I mis-read this.  V1 means metadata schema v1.  So the v1 is definitely needed.

**Comment by hughsie** [comment]
I think JCat solves most of this. I still need to wire up the multiple metadata versions, but that's for another day.
