### ISSUE TITLE
How does fwupd match devices with their correct firmware updates?

### ISSUE THREAD

**Issue by stoiandan** [fwupd/lvfs-website#473]
I've been reading the [documentation](https://lvfs.readthedocs.io/en/latest/intro.html#fwupd) these days and I have question on how `fwupd` matches firmware updates released by vendors with the targeted device.

The documentation states:

> Internally fwupd creates a device with a unique ID, and then a number of GUIDs are assigned to the device by the provider. It is these GUIDs specified in the update metadata file that are used to match a firmware file to a device

Maybe this is going to far but:
1. Does fwupd create the device? Is the deivce not already created by the OS?
2. Fwupd created a device and then assigns it a ID, all clear. Then it is stated that the OEMs assign a number GUIDS to the device.
This is where I'm a bit lost, first of all, why do the OEMs assign multiple GUIDs to a single device and not just one? 
Second, what, it is unclear to me what is the relationship between the ID assigned by `fwupd` and the ones assigned by  the OEM. 
I've seen there is a deeper explanation on the [Metadata section](https://lvfs.readthedocs.io/en/latest/metainfo.html), but it's still not clear. If I'll understand this, I'd like to propose a diagram to show the relationship between these IDs. I'd could draw it :) 
Thank you in advance!
Dan

**Comment by hughsie** [comment]
>  fwupd create the device? Is the deivce not already created by the OS

fwupd creates a fwupd-centric version of the device. We don't actually register anything with the kernel, but we do look at the kernel devices (and do some probing ourselves) to get the data we need.

> why do the OEMs assign multiple GUIDs to a single device and not just one?

Lets use a USB device as an example. By default we create ~2 InstanceIDs for the device:

    │     GUIDs:               4ba9addf-8355-5b02-ad3b-3d4edf033440 ← USB\VID_17EF&PID_305B&REV_5011
    │                          c2e3d4d7-0ad1-5e2b-a9e7-c92f4884bfe6 ← USB\VID_17EF&PID_305B

So if the vendor wants the firmware to apply to device 17EF:305B (any version!) then they can use `c2e3d4d7-0ad1-5e2b-a9e7-c92f4884bfe6` as the GUID in the metainfo.xml file.

If they only want to update 17EF:305B and **only** version 5011 they can use `4ba9addf-8355-5b02-ad3b-3d4edf033440` which will not match the hardware when it's on version 5000 for example.

For some vendors this isn't enough, and they have to restrict this further, for instance to device 17EF:305B and **only** devices with a SPI chip with ID C220. A custom plugin allows adding "extra" insance IDs to a device for this purpose. This is what VIA do for instance:

    │     GUIDs:               4ba9addf-8355-5b02-ad3b-3d4edf033440 ← USB\VID_17EF&PID_305B&REV_5011
    │                          c2e3d4d7-0ad1-5e2b-a9e7-c92f4884bfe6 ← USB\VID_17EF&PID_305B
    │                          6201fecc-1641-51f6-a6d2-38a06d5476bf ← VLI_USBHUB\SPI_C220
    │                          64b8887a-d2a7-5e22-8eb3-411ea1c02fab ← USB\VID_17EF&PID_305B&SPI_C220&REV_5011
    │                          93380547-df10-57d0-adb4-f4389f7373a3 ← USB\VID_17EF&PID_305B&SPI_C220

Does that help?

**Comment by stoiandan** [comment]
I think I I understand now, thank you Richard!
So the main idea is that there are 'subversions' (so to speak) of the same hardware, and you might want to match a more general or narrow target. Hope, I'm not wrong.


Thank you!
