### ISSUE TITLE
Firmware keeps downgrading to testing

### ISSUE THREAD

**Issue by superm1** [fwupd/lvfs-website#482]
This firmware https://fwupd.org/lvfs/firmware/1915 keeps getting downgraded to testing from some bad reports.  Several of them are invalid now (such as:)

* can not flash firmware 01.00.00.00. only firmware 00.00.00.17 -> 00.00.00.23 can be flashed
Is only pre-production hardware

* device version not updated on success, 05.03.10 != 5.03.010
was a fwupd bug that is fixed

* ID a455a3a21752e5d31c228f1f5b51761dad88a432 was not found, UpdateState=failed, VersionNew=01.00.00.00, VersionOld=00.00.00.18
this is preproduction hardware that can't accept the new FW.

There are no new bad reports, but it keeps getting kicked back to testing again every time I try to get it back to stable.  Maybe the counters need to be reset on the channel move?

**Comment by hughsie** [comment]
I've deleted some of the failing reports for pre-production hardware, and also bumped the limits in https://fwupd.org/lvfs/firmware/1915/limits -- and then moved it to stable again.

> Maybe the counters need to be reset on the channel move?

It's not really a counter, it's counting the failed reports each time. I think in this kind of case we need to add known issues, or just lower the auto-downgrade limits for the firmware.

**Comment by hughsie** [comment]
Ohh, some of the stats takea few hours to regenerate, so don't look at the percentage too closely yet.
