### ISSUE TITLE
Old microcode test false positive discussion

### ISSUE THREAD

**Issue by superm1** [fwupd/lvfs-website#494]
A team member recently uploaded a firmware that failed the old microcode test.  It was waived, but I dug in a little more to see details.

Here was the message:
```
Downgraded Intel CPU microcode detected: CPUID:0x806eb Platform:0xd0 version 0xa4 (released on 20181025) is older than latest released version 0xb8 (released on 20190330) found in Latitude 5X00/Precision 3540 System Update v1.4.2
```

Shards from 1.4.2:
https://fwupd.org/lvfs/components/3131/shards

Shards from 1.6.5:
https://fwupd.org/lvfs/components/4339/shards

As I can tell 1.4.2 contains one copy of the microcode for that CPU, but 1.6.5 contains 2 copies.
The 2 copies have one with a really old date (2018 like mentioned) but also a new date (20190814).

So I'm wondering is this actually a test/extraction failure, or just weird that there are actually two copies in the firmware binary somehow?

**Comment by hughsie** [comment]
I actually see 5 microcodes in 1.6.5:

    PYTHONPATH=. ./env/bin/python ./plugins/uefi-extract/__init__.py firmware.bin
    3f0229ad-0a00-5269-90cf-0a45d8781b72 com.intel.Microcode.000806EB.000000D0 9cd060e4ee7652f1c35eff6eca9fec8512f899025e3090ac2425c06e45c3afe7
    cpuid 000806EB
    platform 000000D0
    version 000000C6
    yyyymmdd 20190814
    size 00018800
    checksum 615B03A6
    3f0229ad-0a00-5269-90cf-0a45d8781b72 com.intel.Microcode.000806EC.00000094 ba31fca2d673d264b297de5929fe53437299163ea491f0dff91f0b3817f7e888
    cpuid 000806EC
    platform 00000094
    version 000000C6
    yyyymmdd 20190814
    size 00018800
    checksum F8A49D59
    3f0229ad-0a00-5269-90cf-0a45d8781b72 com.intel.Microcode.000806EC.00000090 5a234c648e657803d96eb242b4b84d656ec3739d8e4ece9037bd42a2d1b54f53
    cpuid 000806EC
    platform 00000090
    version 000000AA
    yyyymmdd 20181129
    size 00018000
    checksum D5273BEF
    3f0229ad-0a00-5269-90cf-0a45d8781b72 com.intel.Microcode.000806EB.000000D0 64006c2173ca7b0167958e3b14ef240d0aa26c2cd63f30eaa6c35bd37fc7efbc
    cpuid 000806EB
    platform 000000D0
    version 000000A4
    yyyymmdd 20181025
    size 00018400
    checksum CEFB81AB
    3f0229ad-0a00-5269-90cf-0a45d8781b72 com.intel.Microcode.000806EA.000000C0 513538880467e3f526ffbd8ef80fcb448ab4f829683f26bc863aeca9964295ac
    cpuid 000806EA
    platform 000000C0
    version 0000009E
    yyyymmdd 20181018
    size 00018000
    checksum B04F551D

> or just weird that there are actually two copies in the firmware binary somehow

Maybe you could ask the firmware team why old versions are being included now? The platform is different between the versions, but to me it looks like both the old and the new microcode versions are being shipped for the same processor in the new update?

**Comment by superm1** [comment]
It looks like either multiple CPU stepping or multiple CPU models too (not sure). I'll ask around further.

**Comment by hughsie** [comment]
@superm1 did you get anywhere here?

**Comment by superm1** [comment]
The conversation went stale.  Thanks for the reminder.  I'll ping again.

**Comment by superm1** [comment]
This conversation came up again and confirmed that it's expected behavior for now on these platforms and the test is doing the right thing.
