### ISSUE TITLE
Allow vendor anchor on devices page

### ISSUE THREAD

**Issue by albert-astals-cid-kdab** [fwupd/lvfs-website#513]
On https://fwupd.org/lvfs/vendors/ i can do https://fwupd.org/lvfs/vendors/#dell to end up in Dell's description, but on https://fwupd.org/lvfs/devices/ in can't and it'd be really handy to send around saying "i know you have a dell, check if it's in the supported list" or "it seems this laptop is nice, let's ee if it's supported before buying it"

**Comment by hughsie** [comment]
Does the search bar work for checking a specific model?

**Comment by albert-astals-cid-kdab** [comment]
Yes it does, but sometimes it's better to list to the exhaustive list because otherwise my brain thinks  "maybe the search failed because it's not so good", don't know if I'm explaining myself correctly
