### ISSUE TITLE
search sets csrf_token in url

### ISSUE THREAD

**Issue by dingens** [fwupd/lvfs-website#539]
Using the search bar on the top of the page, you end up on an address like `https://fwupd.org/lvfs/search?csrf_token=XXX&value=searchstring`.

As users might share this link to the search results page, they might reveal their csrf token. I don't know of a concrete way to abuse this, but as it is not necessary to include the `csfr_token` here, it should probably just be removed just to be safe.

**Comment by hughsie** [comment]
If we POST the search form then the user won't get the search query (that they could share) in the URL at all, right?

**Comment by dingens** [comment]
Right. From an usability perspective, I'd strongly recommend against this.

But note that urls like `https://fwupd.org/lvfs/search?value=linux` work just fine (which is no problem because searching is not an action that changes data and thus need not be protected), so I think the hidden form field could just be removed in the search form (and possibly in other places)
