### ISSUE TITLE
LVFS is parsing hex versionformats as version `None`

### ISSUE THREAD

**Issue by superm1** [fwupd/lvfs-website#542]
Both of these two devices were uploaded to embargo:

https://fwupd.org/lvfs/firmware/3865
https://fwupd.org/lvfs/firmware/3849

The Versions being recognized are `None` though, which seems odd.  

I pulled down the CAB for the first and noticed release like this:
```
  <releases>
    <release version="0xca" date="2020-03-09" urgency="low">
```

Also multiple versionformats are getting applied; plain and hex, but the minimum version is 1.4.0 so it doesn't need the fallback version formats.

Haven't seen what this does to a system yet, but that all looks problematic to me.

**Comment by hughsie** [comment]
> The Versions being recognized are None though, which seems odd.

The uwsgi server needed restarting to use the new models.py, my apologies. I've restarted it now and the versions seem to show correctly.

> multiple versionformats are getting applied; plain and hex

We don't conditionalize the versionformats fallback to a specific version. We certainly could (as we know the fwupd release a verfmt was added in. What do old versions of fwupd do if they encounter an unknown-to-them version format? I assume the component gets ignored anyway as it's not going to have the FuDevice in question, but it's probably worth checking.

**Comment by hughsie** [comment]
Also, what do you think about a new category for microcode updates? I'm not sure I like the "Microcode" name in https://fwupd.org/lvfs/components/4767 -- Microcode for *what*?

**Comment by superm1** [comment]
> Also, what do you think about a new category for microcode updates? I'm not sure I like the "Microcode" name in https://fwupd.org/lvfs/components/4767 -- Microcode for _what_?

In this case it's CPU microcode.  I could try to influence the team to use a better `Name` for the XML strings if you can think of one.

I don't think that it needs a new category, CPUs are devices that the microcode gets loaded onto.  So Device seems to make sense to me.

**Comment by hughsie** [comment]
> use a better Name for the XML strings

<name> isn't supposed to refer to the type firmware, it's supposed to refer to the name of thing that's being installed onto. So for instance, a suitable <name> would be `Intel i7-6820HQ CPU`

> CPUs are devices

I think devices in the LVFS sense are referring to discrete devices that can be removed. With a microcode category the update would appear as:

`Intel i7-6820HQ CPU Microcode Update`

which is much better than

`Microcode Device Update`

... the latter being almost useless to the user.

**Comment by superm1** [comment]
> Intel i7-6820HQ CPU

I don't think the CPU microcode actually exposes a name like this.  The branding is something that the silicon provider decides when it's right about to ship.  For example on the system i'm typing this on it's using an older kernel and `/proc/cpuinfo` shows:

```
model           : 142
model name      : 06/8e
```

>Intel i7-6820HQ CPU Microcode Update

If the team tells me it's not possible to know the name of the CPU at the time of XML build, in lieu of that maybe changing it to "CPU Microcode update" would be better.

**Comment by hughsie** [comment]
> If the team tells me it's not possible to know the name of the CPU at the time of XML build

Do we know if it's an Intel or AMD CPU? `Intel CPU Microcode Update` is still way more useful than `Microcode Device Update`

**Comment by superm1** [comment]
I'm not sure, I'll have to check.  If we don't know, I suppose it's possible to do some deduping with the new `cpu` plugin...

**Comment by hughsie** [comment]
Could you do a PRs for a `X-Microcode` category please? It's be lvfs-website, fwupd and gnome-software too. Even `CPU Microcode Update` is better than `Microcode Device Update`

**Comment by superm1** [comment]
https://github.com/fwupd/lvfs-website/pull/565
https://github.com/fwupd/fwupd/pull/1948

**Comment by superm1** [comment]
https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/437
