### ISSUE TITLE
Re-written version format causes problems for hex

### ISSUE THREAD

**Issue by superm1** [fwupd/lvfs-website#548]
I've gotten a report that a CAB built locally works properly on a system but that it's failing when uploaded and installing via LVFS.

I think this is because LVFS is rewriting the CAB release information.

The particular error: "Specified firmware is older than installed "0x15302529 < 15302529".  Normally I would have expected that it was already installed (and need to use reinstall to reinstall it).

**Comment by superm1** [comment]
The particular firmware is https://fwupd.org/lvfs/firmware/3849

**Comment by superm1** [comment]
Actually this might have been a (non-obvious) operator error looking at the LVFS log - I see it was set to NVME device update, but this is actually supposed to be UEFI device update.  So it probably was tagging to the wrong device.  I've adjusted it, and i'll ask them to re-test.

**Comment by superm1** [comment]
The CAB doesn't appear to have re-generated though with the new metadata... Can you kick it?

**Comment by hughsie** [comment]
I see VFS::UpdateProtocol=org.uefi.capsule in the cab file; is it possible the embargo metadata wasn't regenerated?

**Comment by superm1** [comment]
Is the rebuild of the CAB on a cron job?  I see it updated now too.  I'll ask for re-testing.

**Comment by hughsie** [comment]
> Is the rebuild of the CAB on a cron job?

Yes, i believe it's every 10 minutes.

**Comment by superm1** [comment]
Confirmed that this is sorted now, thanks.
