### ISSUE TITLE
Python3 app.wsgi shebang

### ISSUE THREAD

**Issue by 0xfede7c8** [fwupd/lvfs-website#597]
The app.wsgi file has a shebang pointing to the system wide python3 installation:

``` python
#!/usr/bin/python3
```

This doesn't make use of the python installation in the virtual environment one is supposed have active when running app.wsgi

**Proposal:**

changing it to 

``` python
#!/usr/bin/env python3
```

This will look into the current PATH for the python binary

**Comment by hughsie** [comment]
I thought https://jmmv.dev/2016/09/env-considered-harmful.html was valid for this case? I normally run `./env/bin/python ./foo.py` to make sure the right python is being run.

**Comment by 0xfede7c8** [comment]
Hm, I was not familiar with those arguments to not use bin/env.
Cool. Better to be explicit and safe.

Closing then as this was already contemplated.

**Comment by 0xfede7c8** [comment]
=
