### ISSUE TITLE
Remove users that haven't logged in for a year

### ISSUE THREAD

**Issue by superm1** [fwupd/lvfs-website#601]
Currently LVFS users remain indefinitely in the service.  As people leave companies the data stored in LVFS matching their names should not also remain.  Proposed flow:

1. Daily, check how long since a user logged in.
2. If a user hasn't logged in > 1 year, send them an email to check if they want to keep their account.
3. If a user hasn't logged in > 1 year and 1 week, destroy private data that corresponds to them.

Proposed destroy:
1. Rename their "Display Name" to "Legacy User" or "User $UID"
2. Adjust their email address to anonymous_user_$UID@domain.com (where domain is the OEM or IHV domain).
3. Disable the user's account.

This has the "possibility" that a user remains at a company, doesn't use LVFS for a year, ignores the email and tries to use it again and opens a new account but I think that's OK.

**Comment by hughsie** [comment]
> If a user hasn't logged in > 1 year and 1 week

I think it needs to be a whole lot more. Counter proposal:

* Every day check for users who have not logged in for over 1 year
* If over 1y 6weeks, disable account like you suggest,
* If otherwise send email and store nag timestamp

**Comment by superm1** [comment]
Seems fine to me.

**Comment by hughsie** [comment]
Fixed in https://github.com/fwupd/lvfs-website/pull/607
