### ISSUE TITLE
FIRMWARE_BASEURI(https://fwupd.org/downloads/) is broken with 404 error

### ISSUE THREAD

**Issue by Bambooin** [fwupd/lvfs-website#608]
The https://fwupd.org/downloads/ found in firmware folder README.txt is broken.

https://github.com/fwupd/lvfs-website/blob/364dda45a5a2211a81e3affe674390925b64597a/lvfs/pluginloader.py#L103

**Comment by hughsie** [comment]
The base directory is protected to disallow browsing. What did you expect to see when you visited the basedir?

**Comment by Bambooin** [comment]
I want to download firmware, as the README.txt manifests.

This firmware archive was signed by the LVFS on xx and was made available
from https://fwupd.org/downloads/.

This is the file.
[README.txt](https://github.com/fwupd/lvfs-website/files/4608120/README.txt)
