### ISSUE TITLE
Setting glob for known issues on plugin causes LVFS timeout

### ISSUE THREAD

**Issue by superm1** [fwupd/lvfs-website#626]
For this particular known issue:
https://fwupd.org/lvfs/issues/25/details

I tried to set Plugin to a glob so it could be `synaptics*mst` and match both old and new fwupd versions but this failed and the page times out. So for now it's set to `synapticsmst` which only matches the new versions of fwupd.

**Comment by hughsie** [comment]
Right, globs are CPU intensive the way I implemented them. Could we have two rules with the different plugin names for now, and then I'll rework the rules engine when I'm back from PTO?

**Comment by superm1** [comment]
Yeah I tried to make a second rule, but it doesn't like pointing to the same URL..

**Comment by superm1** [comment]
Maybe point to the URL with a # at the end.  Github thinks those are the same.

**Comment by hughsie** [comment]
> Maybe point to the URL with a # at the end

Right. Hack the system. :)

**Comment by superm1** [comment]
Yup, that works 🙉

**Comment by hughsie** [comment]
Okay deployed, yell if you see this any more. It's certainly a lot, lot, faster for me.

**Comment by superm1** [comment]
It's a lot faster, but I think some reports are "missing" now.  I see on https://fwupd.org/lvfs/firmware/3829 that it has 15 success and 3 fail, but then clicking the links I only see 1 "fail" and 12 success.

I thought maybe known issues was conflating it but On the fail page there are 7 waived as known issues, so that still doesn't add up.

**Comment by hughsie** [comment]
I think we're only showing the most recent 10:

    reports_unfiltered = stmt.order_by(Report.timestamp.desc()).limit(10).all()

Maybe we make the limit a bit higher? Or make it configurable?

**Comment by superm1** [comment]
I thinkin all fail circumstances I'd rather see all the reports, so maybe split it across a page of 10 or so if it's too busy and long.  Or even better a CSV with the report data would be useful to identify success and fail trends :)

**Comment by hughsie** [comment]
No, I'm taking rubbish. The limit there is 100, and I see 20 reports as the admin.

**Comment by hughsie** [comment]
Is it plausible we need to update `report_failure_cnt` when we add a new known issue? The cached count is only updated very 24h by the cron script. Did you perhaps add a new issue?

**Comment by superm1** [comment]
I haven't added new issues since early last week, so no that can't be it.

**Comment by hughsie** [comment]
> so no that can't be it

It can be if the cron script is OOMing :) https://github.com/fwupd/lvfs-website/commit/f45af181f5a59ba48c1f13add7f8a494298404ad

Can you check it's sane now please?

**Comment by superm1** [comment]
Bigger dataset problems I guess :)

Hopefully that didn't lead to any other firmware getting demoted by the reports getting processed wrong for known issues.  The numbers certainly approached the threshold of demotion from the last calculation before you fixed it.

Looks good now, thanks!
