### ISSUE TITLE
Website typo

### ISSUE THREAD

**Issue by pauloxnet** [fwupd/lvfs-website#660]
There's a typo in the website page: "LVFS: Users"
https://fwupd.org/lvfs/docs/users

In the section Using the D-Bus API is present a duplicate `$` siymbol and is reported this code:
```shell
$ $ gdbus call --system --dest org.freedesktop.fwupd --object-path / --method org.freedesktop.fwupd.GetDevices
```

instead of :

```shell
$ gdbus call --system --dest org.freedesktop.fwupd --object-path / --method org.freedesktop.fwupd.GetDevices
```

**Comment by hughsie** [comment]
Hey Paolo -- thanks for this; I'm a pretty bad documentation author. Would you be able to do a pull request for this change? I'm sure there are other typos and it would be great if you could have a look and see what else you can find. Thanks!

**Comment by pauloxnet** [comment]
Hi Richard, I created the PR with the fix for the typo. I'll try later to find other typos.

**Comment by hughsie** [comment]
Merged, thanks!
