### ISSUE TITLE
LVFS Is losing LVFS::UpdateMessage key on WD19's uploads

### ISSUE THREAD

**Issue by superm1** [fwupd/lvfs-website#662]
In https://github.com/fwupd/fwupd/issues/2185 @sitnik reported that there was no message after the updated completed telling them that the update will finish after dock is unplugged.  I dug a little deeper and I think that LVFS didn't write it into the release.

The `ec.metainfo.xml` should have had a key `LVFS::UpdateMessage`, and I don't see that present.  Checking on a locally built XML file that key is added by the CAB building service.

The message was supposed to be: `Updates will complete after the dock is unplugged.  The dock will be unavailable for approximately 1 minute`

**Comment by hughsie** [comment]
https://fwupd.org/lvfs/components/2510/update has no `LVFS::UpdateMessage` -- is it possible that we stripped it by accident when resigning?

We added this last:

    86429815b344da4499d259f00fb55def9386c38b
    Author: Richard Hughes <richard@hughsie.com>
    Date:   Fri Apr 10 10:22:51 2020 +0100

        Add support for LVFS::UpdateMessage

which was after:

    commit 519fa2c2e5ef15c045d2c9fa671aa76236efc16a
    Author: Richard Hughes <richard@hughsie.com>
    Date:   Mon Mar 2 20:08:32 2020 +0000

        Rewrite the metainfo when signing the firmware

...but I don't see that firmware being re-signed in the meantime. Actually, perhaps it never made it into the AppStream metadata at all.

Do all the com.dell.wd19cd357cf1.firmware components need this metadata set? Do any other components of the WD19* docks need this too? If so, I can just update the database and resign the firmware to fix everything up.

**Comment by superm1** [comment]
Yeah that was my thought it was gone from the resigning at some point since the XML got rewritten.

It's just the EC that needs it (IE `WD19/WD19DC/WD19TB Device Update`).

**Comment by hughsie** [comment]
I've modified https://fwupd.org/lvfs/firmware/1915 and https://fwupd.org/lvfs/firmware/3829 for you -- just the EC device. The firmware has re-signed, but it'll still take ~2 hours to rebuild testing and stable.

**Comment by superm1** [comment]
On another one that isn't public it looks like it's still there, so I would say it looks like an artifact of the timing of those two commits (https://fwupd.org/lvfs/firmware/4170).  So I think we're good here. Thanks~
