### ISSUE TITLE
Oauth users are getting an error "Unable to manage authentication"

### ISSUE THREAD

**Issue by superm1** [fwupd/lvfs-website#713]
I notice this recently that several new users with OAuth based accounts are having errors at `/lvfs/users/qrcode` with the error:
"Permission denied: Unable to manage authentication"

**Comment by hughsie** [comment]
I don't think OAuth users are allowed to enroll into 2FA on the LVFS... How are they getting to /lvfs/users/qrcode?

**Comment by superm1** [comment]
That was my expectation too.  So I was worried there might be an unexpected flow that is leading them there.  I don't have a screenshare from any of them, but they're both new users to LVFS.

**Comment by superm1** [comment]
I can reproduce it just by visiting profile page as well with my account.

**Comment by hughsie** [comment]
> I can reproduce it just by visiting profile page as well with my account.

Just visiting? Do you see the `Using 2 factor authentication secures your account more than just using a password` text? It should all be hidden behind a `{% if g.user.check_acl('@manage-password') %}` which only returns true for `self.auth_type == 'local'`....

**Comment by superm1** [comment]
Just visiting, not doing anything with the page.  I don't see that phrase though now.

**Comment by hughsie** [comment]
Okay, this should fix it: https://github.com/fwupd/lvfs-website/commit/d75fd9174e4de05acae15a36fb46e12fbc807bd3

I've just deployed it, can you try again pls.

**Comment by superm1** [comment]
Yup looks good
