### ISSUE TITLE
Update link on https://fwupd.org/lvfs/devices/

### ISSUE THREAD

**Issue by mendel5** [fwupd/lvfs-website#720]
On the web page https://fwupd.org/lvfs/devices/ in the section "Devices supported by the LVFS" the words "LVFS website" link to [https://github.com/hughsie/lvfs-website/issues](https://github.com/hughsie/lvfs-website/issues) but should instead link to [https://github.com/fwupd/lvfs-website/issues](https://github.com/fwupd/lvfs-website/issues).

The link gets redirected so it's not that much of an issue but maybe we can still fix it.

**Comment by hughsie** [comment]
Lets fix both in #722

**Comment by mendel5** [comment]
Fixed with https://github.com/fwupd/lvfs-website/pull/723
