### ISSUE TITLE
Vendorlist: What does "recently" mean here?

### ISSUE THREAD

**Issue by mendel5** [fwupd/lvfs-website#721]
When I go to https://fwupd.org/lvfs/vendors/#lenovo_thinkpad it says "Responsible for 759 firmware files, 210 uploaded recently". Of course these numbers will change when Lenovo uploads more firmwares.

But what does "recently" mean in "210 uploaded recently"? Which time frame is used to calculate the 210?

Instead of "recently" we should write the actual time frame, e.g. "210 uploaded in the last month / last year", etc. That would be more precise and give people a better understanding.

Edit:
- https://github.com/fwupd/lvfs-website/blob/master/lvfs/vendors/templates/vendorlist.html#L37
- https://github.com/fwupd/lvfs-website/blob/master/lvfs/models.py#L475

**Comment by hughsie** [comment]
recently in this case is 25 weeks: https://github.com/fwupd/lvfs-website/blob/master/lvfs/models.py#L475

I agree that's a bit of a random number. Maybe it should be 52 weeks, i.e. one year. Could you do a pull request to change the value in models and also the text in the template please?

**Comment by mendel5** [comment]
> recently in this case is 25 weeks. I agree that's a bit of a random number. Could you do a pull request to change ...

Let's think about Chesterton's fence here for a second:
> “If you don’t see the use of it, I certainly won’t let you clear it away. Go away and think. Then, when you can come back and tell me that you do see the use of it, I may allow you to destroy it.”
> https://en.wikipedia.org/wiki/Wikipedia:Chesterton%27s_fence
> https://fs.blog/2020/03/chestertons-fence/

What was the purpose of choosing exactly 25 weeks and not a different number?

**Comment by hughsie** [comment]
> What was the purpose of choosing exactly 25 weeks and not a different number

The dyslexic in me wonders if it was just typed the wrong way around...

**Comment by mendel5** [comment]
> The dyslexic in me wonders if it was just typed the wrong way around...

That might be possible!

I think a full year (52 weeks) might be a little bit too much to count as recently. Given fwupd was only founded in 2015, a year would be 20 percent of its existence. Of course this percentage decreases as fwupd becomes older...

How about half a year (26 weeks)? Then it could say:
`Responsible for 759 firmware files, 210 uploaded in the last half year`

**Comment by hughsie** [comment]
> How about half a year (26 weeks

It could have been a typo for that too... 

> 210 uploaded in the last half year

I think `210 uploaded in the last 6 months` sounds better personally.

**Comment by mendel5** [comment]
> I think 210 uploaded in the last 6 months sounds better personally.

You're right, that sounds better. Should I create a pull request, Mr. Hughes? :rocket:

**Comment by hughsie** [comment]
> Should I create a pull request, Mr. Hughes

Yes please! Thanks :)

**Comment by mendel5** [comment]
> Yes please!

Here you go: https://github.com/fwupd/lvfs-website/pull/726

**Comment by mendel5** [comment]
https://github.com/fwupd/lvfs-website/pull/726 was merged and deployed successfully. I will close this issue now.
