### ISSUE TITLE
Understanding this project's deployment schedule

### ISSUE THREAD

**Issue by mendel5** [fwupd/lvfs-website#727]
My pull request https://github.com/fwupd/lvfs-website/pull/726 has been merged into the master branch. At the time of writing this there are 12 hours between @hughsie merging my pull request into the master branch and the updated code being deployed in production on https://fwupd.org/ .

On https://lists.linuxfoundation.org/pipermail/lvfs-announce/2020-June/000046.html @hughsie also wrote that
> we tend to deploy [the lvfs-website] straight away to fix serious bugs

Am I correct to assume that the lvfs-website's master branch gets deployed into production on a daily basis?

**Comment by hughsie** [comment]
> lvfs-website's master branch gets deployed into production on a daily basis

It's deployed manually -- and like the quote says, it's often immediately for serious bugs but for the not-so-important stuff it can normally wait for for another high priority fix to land, and then we can deploy them at the same time.

Moving forward, we're moving the infra to the Linux Foundation, and they're setting up a CI/CD pipeline with docker images that get deployed automatically and scaled as required. This timeline is in the weeks/months, so don't get too excited yet :)

**Comment by mendel5** [comment]
> Moving forward, we're moving the infra to the Linux Foundation, and they're setting up a CI/CD pipeline

Does this mean that the main repos of fwupd and lvfs-website will not be hosted on Github anymore?

**Comment by hughsie** [comment]
Good question. Fwupd will stay here, it's highly likely lvfs-website will move to gitlab. Still public like now, just in the other place.

**Comment by mendel5** [comment]
> it's highly likely lvfs-website will move to gitlab

What makes lvfs-website different from fwupd as the latter stays on Github and the former moves to Gitlab? Is there something special about Gitlab?

**Comment by hughsie** [comment]
> Is there something special about Gitlab

IIUC, it's what the Linux Foundation already use to deploy projects into things like docker containers. When you get free gifts you can't dictate the rules :)

**Comment by mendel5** [comment]
> it's what the Linux Foundation already use

This answers my question. I just wanted to understand if the move from Github to Gitlab was motivated by internal or external factors. In my understanding the Linux Foundation counts as an external motivation, which is of course totally fine.
