### ISSUE TITLE
Master branch not up to date?

### ISSUE THREAD

**Issue by mendel5** [fwupd/lvfs-website#728]
The following screenshot has been taken on https://github.com/fwupd/lvfs-website :
![lvfs-website_commits](https://user-images.githubusercontent.com/60322520/88722635-dffc3900-d127-11ea-9997-4cd5f1f767b1.png)

The following screenshot has been taken on https://github.com/fwupd/lvfs-website/branches :
![lvfs-website_master](https://user-images.githubusercontent.com/60322520/88722660-ebe7fb00-d127-11ea-903f-fa816135565c.png)

While both screenshots have only been taken a few seconds apart, you can see that according to the first picture the last commit happened 6 hours ago while according to the second picture the master branch was updated 4 days ago (yellow highlighting). To me it doesn't make sense that one says 6 hours and the other one says 4 days. As far as I can tell the number in picture 2 should also be 6 hours, right?

**Comment by hughsie** [comment]
> As far as I can tell the number in picture 2 should also be 6 hours, right?

I think so. I believe this is a github bug, although I'm not exactly sure where it should be reported :(

**Comment by superm1** [comment]
I think it's time in commit message versus time it landed on the branch no?

**Comment by mendel5** [comment]
> I believe this is a github bug

Strangely the numbers within the fwupd repo are identical (see https://github.com/fwupd/fwupd/commits/master and https://github.com/fwupd/fwupd/branches ) but are different within the lvfs-website repo (see https://github.com/fwupd/lvfs-website/commits/master and https://github.com/fwupd/lvfs-website/branches ).
