### ISSUE TITLE
Incosistent design/ layout on lvfs-website regarding buttons and links

### ISSUE THREAD

**Issue by mendel5** [fwupd/lvfs-website#740]
When comparing the web pages https://fwupd.org/lvfs/firmware/new and https://fwupd.org/lvfs/devices/ you notice that on the former there is a button "Details" that links the device page while on the latter the devices are linked directly (=no button).

For reasons of simplicity and concistency I would like to propose removing the "Details" button on https://fwupd.org/lvfs/firmware/new and linking the devices directly in the column "Hardware".

**Comment by hughsie** [comment]
The https://fwupd.org/lvfs/firmware/new does seem a bit dense, and probably doesn't work very well on small screens. We should probably put each firmware in a bootstrap card.

**Comment by hughsie** [comment]
![Screenshot_2020-08-03 LVFS New Firmware](https://user-images.githubusercontent.com/151380/89166712-56f36080-d572-11ea-9f22-e5aa0e69bde2.png)

**Comment by hughsie** [comment]
How about something like this?
![Screenshot_2020-08-03 LVFS New Firmware(1)](https://user-images.githubusercontent.com/151380/89167966-07ae2f80-d574-11ea-9f7e-fda0adba5c08.png)

**Comment by mendel5** [comment]
@hughsie Yes, that looks very nice!
