### ISSUE TITLE
CVEs and INTEL-SAs missing in description on LVFS website

### ISSUE THREAD

**Issue by BjoernDaase** [fwupd/lvfs-website#758]
It looks like CVEs and INTEL-SAs are missing in description on LVFS website. Even though they are listed separately in a "Fixed issues" section further down, the description looks absolutely broken:

![image](https://user-images.githubusercontent.com/24682367/90750843-adcc9a00-e2d5-11ea-9c16-dd91fc5b3f79.png)

And this is how it looks on Dell website:
![image](https://user-images.githubusercontent.com/24682367/90750952-cf2d8600-e2d5-11ea-97d7-1cac897826de.png)

This is the update on the LVFS website: https://fwupd.org/lvfs/devices/com.dell.uefi7ceaf7a8.firmware.
For comparison, this is it on Dells website: https://www.dell.com/support/home/de-de/drivers/driversdetails?driverid=9d00x&oscode=biosa&productcode=xps-13-9370-laptop.

**Comment by hughsie** [comment]
I've sent a snotty email to the person uploading the firmware and pushed it back to testing. I've told them to fix it. Thanks for the heads up.

**Comment by BjoernDaase** [comment]
And it's broken again....

https://fwupd.org/lvfs/devices/com.dell.uefi7ceaf7a8.firmware

**Comment by hughsie** [comment]
I've fixed up that firmware, but also opened https://github.com/fwupd/lvfs-website/pull/785 so that it stops happening.
