### ISSUE TITLE
Where can I find firmware uploaded by MSI?

### ISSUE THREAD

**Issue by mendel5** [fwupd/lvfs-website#763]
I would like to buy a new mainboard from MSI (aka [Micro-Star International](https://en.wikipedia.org/wiki/Micro-Star_International)).

In the vendor list of the LVFS (https://fwupd.org/lvfs/vendors/#msi ) it says that MSI
> is uploading firmware on behalf of other vendors.

When I search for MSI at https://fwupd.org/lvfs/search?value=msi only the vendor is shown but no devices or firmwares.

A search on Google at https://www.google.com/search?q=site%3Afwupd.org+%22msi%22 also yields no results.

Where can I find any kind of firmware uploaded by MSI?

**Comment by hughsie** [comment]
There are no OEM boards supported by MSI, although they act as an ODM to another OEM. That's all I can tell you I'm afraid.

**Comment by mendel5** [comment]
So the reason I cannot see the firmwares uploaded by MSI's account to the LVFS is not because it's technically not possible to display this information but because MSI does not want to reveal who the ODM client is?

**Comment by hughsie** [comment]
> because MSI does not want to reveal who the ODM client is

Correct. None of the "own brand" hardware seems supported.

**Comment by mendel5** [comment]
Alright, good to know.
