### ISSUE TITLE
Feature request: Changelog on the LVFS vendor list

### ISSUE THREAD

**Issue by dal00** [fwupd/lvfs-website#93]
Hi!
It would be great if there was a ChangeLog on the LVFS vendor list because it's getting hard to see new updates. I see a lot of comments about emails being sent out but then It's hard to know when and what they answered. Maybe an rss feed for the ChangeLog as well?

https://fwupd.org/vendorlist <-this page

**Comment by hughsie** [comment]
Can you clarify the use case you have please? Do you want to know about new vendors joining the LVFS, or the status change (e.g. "investigating support" -> "7 models of hardware are supported"). Maybe something like a "news" section on the front page might solve both issues?

**Comment by superm1** [comment]
Along the lines of a news section I wonder if it might be useful to note new firmware releases there too?  I like the idea of an automated RSS feed to hear what all is changing in LVFS be it vendors joining, new systems released, new firmware released etc.

**Comment by dal00** [comment]
@hughsie Not sure exactly but I just want it to be easy to see updates to the page. For example I have different hardware from manufacturer X and Y and I want to track their status. How are they responding to the requests sent by email? New support available? New models supported from manufacturer X?
It is very hard to track changes on the list. Especially if new entries pop up.
Does this make any sense?

**Comment by hughsie** [comment]
I think https://fwupd.org/lvfs/devicelist is the best of what we can provide; working with vendors is normally a pretty secretive thing and they don't want to be splashed on front on Phoronix just because one engineer created an account for testing. Sorry.
