### ISSUE TITLE
Adjust analytics to present more data to analyst permission

### ISSUE THREAD

**Issue by superm1** [fwupd/lvfs-website#99]
Per some discussion in a PR, can you please expose graphs for the following items:

* pie chart showing the OS break down where known by user agent data (unknown for generic or something)
* pie chart showing fwupd version breakdown
* histogram showing number of downloads made by a single client

Would like to see these exposed both on:

1. Firmware by firmware basis
2. OEM Group basis (all firmware in the OEM group).

**Comment by superm1** [comment]
While making that graph, I also wonder if it would be useful to do a LVFS wide public one at least of the first 2?  I suspect you'd want to cron it's creation though to avoid load if public people can view it.

**Comment by hughsie** [comment]
> pie chart showing the OS break down where known by user agent data

For firmware or for reports? For the former we only recently added the extra bits to the user agent, and at the moment most still say gnome-software/1.2.3 rather than anything very useful. In time the data will be better, but at the moment the data is too skewed to present IMHO. Maybe when F28 and Ubuntu are both next out? 

> pie chart showing fwupd version breakdown

Same as above here. I guess we can build the feature and just enable it when the data is good.

> histogram showing number of downloads made by a single client

What's the rationale here? To spot people abusing the service?

**Comment by superm1** [comment]
>>histogram showing number of downloads made by a single client

>What's the rationale here? To spot people abusing the service?
I see two purposes:
1. When it's per firmware item, to determine there are continual failures by people and they keep downloading and retrying but don't report the failures.  This might not be a good data point per firmware though since the client should keep the file cached I think. You can tell me what g-s does in this instance.

2. (More interesting) When you map it across multiple firmware versions.  To see that people are "continuing" to use the service as new firmware released or they're one time use and never update again.

**Comment by hughsie** [comment]
> can tell me what g-s does in this instance.

Also cache.

> To see that people are "continuing" to use the service as new firmware released

That is useful. What about a bar graph of the number of times a client has downloaded a different firmware for the same hardware? e.g. 5% of people have only ever downloaded one firmware, 50% have downloaded 2, and 45% of people have downloaded all 3. This wouldn't be per-firmware, but could be per-device.

**Comment by superm1** [comment]
>That is useful. What about a bar graph of the number of times a client has downloaded a different firmware for the same hardware? e.g. 5% of people have only ever downloaded one firmware, 50% have downloaded 2, and 45% of people have downloaded all 3. This wouldn't be per-firmware, but could be per-device.

Yes I think that would be great.

**Comment by hughsie** [comment]
> pie chart showing the OS break down
> pie chart showing fwupd version breakdown

I've had a few people comment that this isn't a good idea. I think showing if the same clients are getting different versions of the update for each device model is still useful, but I think the user agent contents should probably remain private. I know it's a tricky balance, and I struggle with the same issues on the ODRS too.

**Comment by superm1** [comment]
There are a few ways to stay on the right side of the tricky balance I think:

1. Looking at it in aggregate (Show charts only - not full user agent strings)
2. Decouple OS version and fwupd version in these charts.
3. Only show a graph detail after say 20 downloads.

As an example say you have a firmware with 100 downloads:
* 30 Fedora 30; some with fwupd 1.2.10 others with gnome-software 3.32
* 20 Ubuntu 16.04; some with fwupd 0.9.8, some with fwupd 1.2.8, others with gnome-software 3.26
* 20 Ubuntu 18.04; all with fwupd 1.2.5 or gnome-software 3.30
* 21 Arch; all with fwupd 1.2.10
* 9 Gentoo; all with fwupd 1.2.10
-------

Then you can show one OS graph that just breaks down like this:
* 30% fedora 30
* 30% Ubuntu 16.04
* 30% Ubuntu 18.04
* 21% Arch
* 9% Other

And you can show a fwupd graph that breaks down like:
* 55% fwupd 1.2.10
* 5% gnome-software 3.32 
* 5% fwupd 0.9.8
* 5% fwupd 1.2.8
* 10% gnome-software 3.26
* 10% fwupd 1.2.5
* 10% gnome-software 3.30

---

I'd think that preserves privacy; you can't even associate a particular fwupd version to an OS release (unless it's an ancient version <cough ubuntu 16.04>)

And even then, that ancient version information is incredibly useful.  I think even outside of individual firmware downloads if you look at it pan LVFS how quickly to deprecate things and how important backports are to older fwupd or gnome-software branches.

**Comment by hughsie** [comment]
> if you look at it pan LVFS how quickly to deprecate things and how important backports are to older fwupd or gnome-software branches.

I think that's useful data for me, but I don't think it's the kind of thing vendors as general need. I think if you (specifically, as the co-maintainer of most of this stuff) need justification for an Ubuntu SRU of fwupd I'd gladly give you some aggregate numbers, but certainly not all the vendors are in the same boat. I'd give the same numbers to the maintainer or the KDE software center with the same logic.

Most of the criticism over the years about the LVFS appears to be about the centralized nature, and the fact it has access to this kind of info. I'm no super keen pouring petrol on those flames, sorry.
